.nh
.TH "GF-ADMIN-LDAP" "1" "May 2026" "" ""

.SH NAME
gf-admin-ldap - Admin ldap API


.SH SYNOPSIS
\fBgf admin-ldap [flags]\fP


.SH DESCRIPTION
Admin ldap API


.SH OPTIONS
\fB-h\fP, \fB--help\fP[=false]
	help for admin-ldap


.SH OPTIONS INHERITED FROM PARENT COMMANDS
\fB--api-key\fP=""
	API Key to authenticate to grafana server (env: GF_API_KEY)

.PP
\fB--base-path\fP="/api"
	Base path for server: useful when using sever behind reverse proxy (env: GF_BASE_PATH)

.PP
\fB--basic-user-password\fP=""
	Basic authentication password (env: GF_BASIC_AUTH_USERNAME)

.PP
\fB--basic-user-username\fP=""
	Basic authentication username (env: GF_BASIC_AUTH_PASSWORD)

.PP
\fB--debug\fP[=false]
	Enable debug logging (env: GF_DEBUG)

.PP
\fB--host\fP="localhost:3000"
	Grafana server host (env: GF_HOST)

.PP
\fB--org-id\fP=0
	Organization ID (env: GF_ORG_ID)


.SH SEE ALSO
\fBgf(1)\fP, \fBgf-admin-ldap-get-ldap-status(1)\fP, \fBgf-admin-ldap-get-user-from-ldap(1)\fP, \fBgf-admin-ldap-post-sync-user-with-ldap(1)\fP, \fBgf-admin-ldap-reload-ldap-cfg(1)\fP
