.nh
.TH "GF-ACCESS-CONTROL-SET-TEAM-ROLES" "1" "Apr 2026" "" ""

.SH NAME
gf-access-control-set-team-roles - Updates team role


.SH SYNOPSIS
\fBgf access-control set-team-roles [flags]\fP


.SH DESCRIPTION
You need to have a permission with action \fBteams.roles:add\fR and \fBteams.roles:remove\fR and scope \fBpermissions:type:delegate\fR for each.

.PP
Body schema (SetTeamRolesCommand):
{
  "includeHidden": boolean,
  "roleUids": [string]
}


.SH OPTIONS
\fB--body\fP=""
	The path to the body json file or json string. For example, --body=/path/to/body.json or --body='{"foo": "bar"}'

.PP
\fB-h\fP, \fB--help\fP[=false]
	help for set-team-roles

.PP
\fB--team-id\fP=0
	TeamID


.SH OPTIONS INHERITED FROM PARENT COMMANDS
\fB--api-key\fP=""
	API Key to authenticate to grafana server (env: GF_API_KEY)

.PP
\fB--base-path\fP="/api"
	Base path for server: useful when using sever behind reverse proxy (env: GF_BASE_PATH)

.PP
\fB--basic-user-password\fP=""
	Basic authentication password (env: GF_BASIC_AUTH_USERNAME)

.PP
\fB--basic-user-username\fP=""
	Basic authentication username (env: GF_BASIC_AUTH_PASSWORD)

.PP
\fB--debug\fP[=false]
	Enable debug logging (env: GF_DEBUG)

.PP
\fB--host\fP="localhost:3000"
	Grafana server host (env: GF_HOST)

.PP
\fB--org-id\fP=0
	Organization ID (env: GF_ORG_ID)


.SH SEE ALSO
\fBgf-access-control(1)\fP
