.nh
.TH "GF-ACCESS-CONTROL-CREATE-ROLE" "1" "May 2026" "" ""

.SH NAME
gf-access-control-create-role - Creates a new custom role


.SH SYNOPSIS
\fBgf access-control create-role [flags]\fP


.SH DESCRIPTION
Creates a new custom role

.PP
Creates a new custom role and maps given permissions to that role. Note that roles with the same prefix as Fixed Roles can’t be created.

.PP
You need to have a permission with action \fBroles:write\fR and scope \fBpermissions:type:delegate\fR\&. \fBpermissions:type:delegate\fR scope ensures that users can only create custom roles with the same, or a subset of permissions which the user has. For example, if a user does not have required permissions for creating users, they won’t be able to create a custom role which allows to do that. This is done to prevent escalation of privileges.

.PP
Body schema (CreateRoleForm):
  description            string
  displayName            string
  global                 boolean
  group                  string
  hidden                 boolean
  name                   string
  permissions            array
  permissions[].action   string
  permissions[].created  string
  permissions[].scope    string
  permissions[].updated  string
  uid                    string
  version                number

.PP
Response schema (CreateRoleCreated.Payload):
  created                string         REQUIRED
  delegatable            boolean
  description            string         REQUIRED
  displayName            string         REQUIRED
  global                 boolean
  group                  string         REQUIRED
  hidden                 boolean
  mapped                 boolean
  name                   string         REQUIRED
  permissions            array
  permissions[].action   string
  permissions[].created  string
  permissions[].scope    string
  permissions[].updated  string
  uid                    string         REQUIRED
  updated                string         REQUIRED
  version                number         REQUIRED


.SH OPTIONS
\fB--body\fP=""
	Request body JSON or path to a JSON file (e.g. --body=/path/to/body.json, --body='{"foo": "bar"}'). The 'Body schema' block above lists fields and types; use --describe-body-jsonschema for a strict JSON Schema.

.PP
\fB--describe-body-jsonschema\fP[=false]
	Print the JSON Schema of the request body and exit without calling the API

.PP
\fB--describe-response-jsonschema\fP[=false]
	Print the JSON Schema of the response payload and exit without calling the API

.PP
\fB-h\fP, \fB--help\fP[=false]
	help for create-role

.PP
\fB--raw\fP[=false]
	Print the raw HTTP response body instead of the decoded payload


.SH OPTIONS INHERITED FROM PARENT COMMANDS
\fB--api-key\fP=""
	API Key to authenticate to grafana server (env: GF_API_KEY)

.PP
\fB--base-path\fP="/api"
	Base path for server: useful when using sever behind reverse proxy (env: GF_BASE_PATH)

.PP
\fB--basic-user-password\fP=""
	Basic authentication password (env: GF_BASIC_AUTH_USERNAME)

.PP
\fB--basic-user-username\fP=""
	Basic authentication username (env: GF_BASIC_AUTH_PASSWORD)

.PP
\fB--debug\fP[=false]
	Enable debug logging (env: GF_DEBUG)

.PP
\fB--host\fP="localhost:3000"
	Grafana server host (env: GF_HOST)

.PP
\fB--org-id\fP=0
	Organization ID (env: GF_ORG_ID)


.SH SEE ALSO
\fBgf-access-control(1)\fP
