.nh
.TH "GF-ADMIN-PROVISIONING-ADMIN-PROVISIONING-RELOAD-ACCESS-CONTROL" "1" "May 2026" "" ""

.SH NAME
gf-admin-provisioning-admin-provisioning-reload-access-control - Yous need to have a permission with action provisioning reload with scope provisioners accesscontrol


.SH SYNOPSIS
\fBgf admin-provisioning admin-provisioning-reload-access-control [flags]\fP


.SH DESCRIPTION
Yous need to have a permission with action provisioning reload with scope provisioners accesscontrol

.PP
Response schema (AdminProvisioningReloadAccessControlAccepted.Payload):
  error    string  Error An optional detailed description of the actual error. Only included if running in developer mode.
  message  string  REQUIRED
                   a human readable version of the error
  status   string  Status An optional status to denote the cause of the error.
                   For example, a 412 Precondition Failed error may include additional information of why that error happened.


.SH OPTIONS
\fB--describe-response-jsonschema\fP[=false]
	Print the JSON Schema of the response payload and exit without calling the API

.PP
\fB-h\fP, \fB--help\fP[=false]
	help for admin-provisioning-reload-access-control

.PP
\fB--raw\fP[=false]
	Print the raw HTTP response body instead of the decoded payload


.SH OPTIONS INHERITED FROM PARENT COMMANDS
\fB--api-key\fP=""
	API Key to authenticate to grafana server (env: GF_API_KEY)

.PP
\fB--base-path\fP="/api"
	Base path for server: useful when using sever behind reverse proxy (env: GF_BASE_PATH)

.PP
\fB--basic-user-password\fP=""
	Basic authentication password (env: GF_BASIC_AUTH_USERNAME)

.PP
\fB--basic-user-username\fP=""
	Basic authentication username (env: GF_BASIC_AUTH_PASSWORD)

.PP
\fB--debug\fP[=false]
	Enable debug logging (env: GF_DEBUG)

.PP
\fB--host\fP="localhost:3000"
	Grafana server host (env: GF_HOST)

.PP
\fB--org-id\fP=0
	Organization ID (env: GF_ORG_ID)


.SH SEE ALSO
\fBgf-admin-provisioning(1)\fP
