.nh
.TH "GF-ACCESS-CONTROL-CREATE-ROLE" "1" "Apr 2026" "" ""

.SH NAME
gf-access-control-create-role - Creates a new custom role


.SH SYNOPSIS
\fBgf access-control create-role [flags]\fP


.SH DESCRIPTION
Creates a new custom role and maps given permissions to that role. Note that roles with the same prefix as Fixed Roles can’t be created.

.PP
You need to have a permission with action \fBroles:write\fR and scope \fBpermissions:type:delegate\fR\&. \fBpermissions:type:delegate\fR scope ensures that users can only create custom roles with the same, or a subset of permissions which the user has. For example, if a user does not have required permissions for creating users, they won’t be able to create a custom role which allows to do that. This is done to prevent escalation of privileges.


.SH OPTIONS
\fB--body\fP=""
	The path to the body json file or json string. For example, --body=/path/to/body.json or --body='{"foo": "bar"}'

.PP
\fB-h\fP, \fB--help\fP[=false]
	help for create-role


.SH OPTIONS INHERITED FROM PARENT COMMANDS
\fB--api-key\fP=""
	API Key to authenticate to grafana server (env: GF_API_KEY)

.PP
\fB--base-path\fP="/api"
	Base path for server: useful when using sever behind reverse proxy (env: GF_BASE_PATH)

.PP
\fB--basic-user-password\fP=""
	Basic authentication password (env: GF_BASIC_AUTH_USERNAME)

.PP
\fB--basic-user-username\fP=""
	Basic authentication username (env: GF_BASIC_AUTH_PASSWORD)

.PP
\fB--debug\fP[=false]
	Enable debug logging (env: GF_DEBUG)

.PP
\fB--host\fP="localhost:3000"
	Grafana server host (env: GF_HOST)

.PP
\fB--org-id\fP=0
	Organization ID (env: GF_ORG_ID)


.SH SEE ALSO
\fBgf-access-control(1)\fP
