.nh
.TH "GF-ADMIN-USERS" "1" "Apr 2026" "" ""

.SH NAME
gf-admin-users -


.SH SYNOPSIS
\fBgf admin-users [flags]\fP


.SH DESCRIPTION

.SH OPTIONS
\fB-h\fP, \fB--help\fP[=false]
	help for admin-users


.SH OPTIONS INHERITED FROM PARENT COMMANDS
\fB--api-key\fP=""
	API Key to authenticate to grafana server (env: GF_API_KEY)

.PP
\fB--base-path\fP="/api"
	Base path for server: useful when using sever behind reverse proxy (env: GF_BASE_PATH)

.PP
\fB--basic-user-password\fP=""
	Basic authentication password (env: GF_BASIC_AUTH_USERNAME)

.PP
\fB--basic-user-username\fP=""
	Basic authentication username (env: GF_BASIC_AUTH_PASSWORD)

.PP
\fB--debug\fP[=false]
	Enable debug logging (env: GF_DEBUG)

.PP
\fB--host\fP="localhost:3000"
	Grafana server host (env: GF_HOST)

.PP
\fB--org-id\fP=0
	Organization ID (env: GF_ORG_ID)


.SH SEE ALSO
\fBgf(1)\fP, \fBgf-admin-users-admin-create-user(1)\fP, \fBgf-admin-users-admin-delete-user(1)\fP, \fBgf-admin-users-admin-disable-user(1)\fP, \fBgf-admin-users-admin-enable-user(1)\fP, \fBgf-admin-users-admin-get-user-auth-tokens(1)\fP, \fBgf-admin-users-admin-logout-user(1)\fP, \fBgf-admin-users-admin-revoke-user-auth-token(1)\fP, \fBgf-admin-users-admin-update-user-password(1)\fP, \fBgf-admin-users-admin-update-user-permissions(1)\fP
