.nh
.TH "GF-ANNOTATIONS-GET-ANNOTATION-TAGS" "1" "May 2026" "" ""

.SH NAME
gf-annotations-get-annotation-tags - Finds annotations tags


.SH SYNOPSIS
\fBgf annotations get-annotation-tags [flags]\fP


.SH DESCRIPTION
Finds annotations tags

.PP
Find all the event tags created in the annotations.


.SH OPTIONS
\fB--describe-response-jsonschema\fP[=false]
	Print the JSON Schema of the response payload and exit without calling the API

.PP
\fB-h\fP, \fB--help\fP[=false]
	help for get-annotation-tags

.PP
\fB--limit\fP=""
	Max limit for results returned. Default: "100"

.PP
\fB--raw\fP[=false]
	Print the raw HTTP response body instead of the decoded payload

.PP
\fB--tag\fP=""
	Tag is a string that you can use to filter tags.


.SH OPTIONS INHERITED FROM PARENT COMMANDS
\fB--api-key\fP=""
	API Key to authenticate to grafana server (env: GF_API_KEY)

.PP
\fB--base-path\fP="/api"
	Base path for server: useful when using sever behind reverse proxy (env: GF_BASE_PATH)

.PP
\fB--basic-user-password\fP=""
	Basic authentication password (env: GF_BASIC_AUTH_USERNAME)

.PP
\fB--basic-user-username\fP=""
	Basic authentication username (env: GF_BASIC_AUTH_PASSWORD)

.PP
\fB--debug\fP[=false]
	Enable debug logging (env: GF_DEBUG)

.PP
\fB--host\fP="localhost:3000"
	Grafana server host (env: GF_HOST)

.PP
\fB--org-id\fP=0
	Organization ID (env: GF_ORG_ID)


.SH SEE ALSO
\fBgf-annotations(1)\fP
