.nh
.TH "GF-ACCESS-CONTROL-SET-ROLE-ASSIGNMENTS" "1" "Apr 2026" "" ""

.SH NAME
gf-access-control-set-role-assignments - Sets role assignments


.SH SYNOPSIS
\fBgf access-control set-role-assignments [flags]\fP


.SH DESCRIPTION
Sets role assignments

.PP
Set role assignments for the role with the given UID.

.PP
You need to have a permission with action \fBteams.roles:add\fR and \fBteams.roles:remove\fR and scope \fBpermissions:type:delegate\fR, and \fBusers.roles:add\fR and \fBusers.roles:remove\fR and scope \fBpermissions:type:delegate\fR\&.

.PP
Body schema (SetRoleAssignmentsCommand):
{
  "service_accounts": [number],
  "teams": [number],
  "users": [number]
}


.SH OPTIONS
\fB--body\fP=""
	Request body JSON or path to a JSON file (e.g. --body=/path/to/body.json, --body='{"foo": "bar"}'). The 'Body schema' block is a type reference; use --describe-body-jsonschema for a strict JSON Schema.

.PP
\fB--describe-body-jsonschema\fP[=false]
	Print the JSON Schema of the request body and exit without calling the API

.PP
\fB--describe-response-jsonschema\fP[=false]
	Print the JSON Schema of the response payload and exit without calling the API

.PP
\fB-h\fP, \fB--help\fP[=false]
	help for set-role-assignments

.PP
\fB--raw\fP[=false]
	Print the raw HTTP response body instead of the decoded payload

.PP
\fB--role-uid\fP=""
	RoleUID


.SH OPTIONS INHERITED FROM PARENT COMMANDS
\fB--api-key\fP=""
	API Key to authenticate to grafana server (env: GF_API_KEY)

.PP
\fB--base-path\fP="/api"
	Base path for server: useful when using sever behind reverse proxy (env: GF_BASE_PATH)

.PP
\fB--basic-user-password\fP=""
	Basic authentication password (env: GF_BASIC_AUTH_USERNAME)

.PP
\fB--basic-user-username\fP=""
	Basic authentication username (env: GF_BASIC_AUTH_PASSWORD)

.PP
\fB--debug\fP[=false]
	Enable debug logging (env: GF_DEBUG)

.PP
\fB--host\fP="localhost:3000"
	Grafana server host (env: GF_HOST)

.PP
\fB--org-id\fP=0
	Organization ID (env: GF_ORG_ID)


.SH SEE ALSO
\fBgf-access-control(1)\fP
