.nh
.TH "GF-ACCESS-CONTROL-SET-USER-ROLES" "1" "May 2026" "" ""

.SH NAME
gf-access-control-set-user-roles - Sets user role assignments


.SH SYNOPSIS
\fBgf access-control set-user-roles [flags]\fP


.SH DESCRIPTION
Sets user role assignments

.PP
Update the user’s role assignments to match the provided set of UIDs. This will remove any assigned roles that aren’t in the request and add roles that are in the set but are not already assigned to the user. Roles mapped through group attribute sync are not impacted. If you want to add or remove a single role, consider using Add a user role assignment or Remove a user role assignment instead.

.PP
You need to have a permission with action \fBusers.roles:add\fR and \fBusers.roles:remove\fR and scope \fBpermissions:type:delegate\fR for each. \fBpermissions:type:delegate\fR  scope ensures that users can only assign or unassign roles which have same, or a subset of permissions which the user has. For example, if a user does not have required permissions for creating users, they won’t be able to assign or unassign a role which will allow to do that. This is done to prevent escalation of privileges.

.PP
Body schema (SetUserRolesCommand):
  global         boolean
  includeHidden  boolean
  roleUids       array

.PP
Response schema (SetUserRolesOK.Payload):
  message  string


.SH OPTIONS
\fB--body\fP=""
	Request body JSON or path to a JSON file (e.g. --body=/path/to/body.json, --body='{"foo": "bar"}'). The 'Body schema' block below lists fields and types; use --describe-body-jsonschema for a strict JSON Schema. [required]

.PP
\fB--describe-body-jsonschema\fP[=false]
	Print the JSON Schema of the request body and exit without calling the API

.PP
\fB--describe-response-jsonschema\fP[=false]
	Print the JSON Schema of the response payload and exit without calling the API

.PP
\fB-h\fP, \fB--help\fP[=false]
	help for set-user-roles

.PP
\fB--raw\fP[=false]
	Print the raw HTTP response body instead of the decoded payload

.PP
\fB--target-org-id\fP=0
	TargetOrgID

.PP
\fB--user-id\fP=0
	UserID [required]


.SH OPTIONS INHERITED FROM PARENT COMMANDS
\fB--api-key\fP=""
	API Key to authenticate to grafana server (env: GF_API_KEY)

.PP
\fB--base-path\fP="/api"
	Base path for server: useful when using sever behind reverse proxy (env: GF_BASE_PATH)

.PP
\fB--basic-user-password\fP=""
	Basic authentication password (env: GF_BASIC_AUTH_USERNAME)

.PP
\fB--basic-user-username\fP=""
	Basic authentication username (env: GF_BASIC_AUTH_PASSWORD)

.PP
\fB--debug\fP[=false]
	Enable debug logging (env: GF_DEBUG)

.PP
\fB--host\fP="localhost:3000"
	Grafana server host (env: GF_HOST)

.PP
\fB--org-id\fP=0
	Organization ID (env: GF_ORG_ID)


.SH SEE ALSO
\fBgf-access-control(1)\fP
