.nh
.TH "GF-ACCESS-CONTROL-LIST-USER-ROLES" "1" "Apr 2026" "" ""

.SH NAME
gf-access-control-list-user-roles - Lists roles assigned to a user


.SH SYNOPSIS
\fBgf access-control list-user-roles [flags]\fP


.SH DESCRIPTION
Lists the roles that have been directly assigned to a given user. The list does not include built-in roles (Viewer, Editor, Admin or Grafana Admin), and it does not include roles that have been inherited from a team.

.PP
You need to have a permission with action \fBusers.roles:read\fR and scope \fBusers:id:<user ID>\fR\&.


.SH OPTIONS
\fB-h\fP, \fB--help\fP[=false]
	help for list-user-roles

.PP
\fB--user-id\fP=0
	UserID


.SH OPTIONS INHERITED FROM PARENT COMMANDS
\fB--api-key\fP=""
	API Key to authenticate to grafana server (env: GF_API_KEY)

.PP
\fB--base-path\fP="/api"
	Base path for server: useful when using sever behind reverse proxy (env: GF_BASE_PATH)

.PP
\fB--basic-user-password\fP=""
	Basic authentication password (env: GF_BASIC_AUTH_USERNAME)

.PP
\fB--basic-user-username\fP=""
	Basic authentication username (env: GF_BASIC_AUTH_PASSWORD)

.PP
\fB--debug\fP[=false]
	Enable debug logging (env: GF_DEBUG)

.PP
\fB--host\fP="localhost:3000"
	Grafana server host (env: GF_HOST)

.PP
\fB--org-id\fP=0
	Organization ID (env: GF_ORG_ID)


.SH SEE ALSO
\fBgf-access-control(1)\fP
