.nh
.TH "GF-ACCESS-CONTROL-LIST-TEAM-ROLES" "1" "May 2026" "" ""

.SH NAME
gf-access-control-list-team-roles - Gets team roles


.SH SYNOPSIS
\fBgf access-control list-team-roles [flags]\fP


.SH DESCRIPTION
Gets team roles

.PP
You need to have a permission with action \fBteams.roles:read\fR and scope \fBteams:id:<team ID>\fR\&.

.PP
Response schema (ListTeamRolesOK.Payload):
  message  string


.SH OPTIONS
\fB--describe-response-jsonschema\fP[=false]
	Print the JSON Schema of the response payload and exit without calling the API

.PP
\fB-h\fP, \fB--help\fP[=false]
	help for list-team-roles

.PP
\fB--raw\fP[=false]
	Print the raw HTTP response body instead of the decoded payload

.PP
\fB--team-id\fP=0
	TeamID


.SH OPTIONS INHERITED FROM PARENT COMMANDS
\fB--api-key\fP=""
	API Key to authenticate to grafana server (env: GF_API_KEY)

.PP
\fB--base-path\fP="/api"
	Base path for server: useful when using sever behind reverse proxy (env: GF_BASE_PATH)

.PP
\fB--basic-user-password\fP=""
	Basic authentication password (env: GF_BASIC_AUTH_USERNAME)

.PP
\fB--basic-user-username\fP=""
	Basic authentication username (env: GF_BASIC_AUTH_PASSWORD)

.PP
\fB--debug\fP[=false]
	Enable debug logging (env: GF_DEBUG)

.PP
\fB--host\fP="localhost:3000"
	Grafana server host (env: GF_HOST)

.PP
\fB--org-id\fP=0
	Organization ID (env: GF_ORG_ID)


.SH SEE ALSO
\fBgf-access-control(1)\fP
