.nh
.TH "GF-ADMIN-LDAP-GET-LDAP-STATUS" "1" "Jun 2026" "" ""

.SH NAME
gf-admin-ldap-get-ldap-status - Attempts to connect to all the configured LDAP servers and returns information on whenever they re available or not


.SH SYNOPSIS
\fBgf admin-ldap get-ldap-status [flags]\fP


.SH DESCRIPTION
Attempts to connect to all the configured LDAP servers and returns information on whenever they re available or not

.PP
If you are running Grafana Enterprise and have Fine-grained access control enabled, you need to have a permission with action \fBldap.status:read\fR\&.

.PP
Response schema (GetLDAPStatusOK.Payload):
  message  string


.SH OPTIONS
\fB--describe-response-jsonschema\fP[=false]
	Print the JSON Schema of the response payload and exit without calling the API

.PP
\fB-h\fP, \fB--help\fP[=false]
	help for get-ldap-status

.PP
\fB--raw\fP[=false]
	Print the raw HTTP response body instead of the decoded payload


.SH OPTIONS INHERITED FROM PARENT COMMANDS
\fB--api-key\fP=""
	API Key to authenticate to grafana server (env: GF_API_KEY)

.PP
\fB--base-path\fP="/api"
	Base path for server: useful when using server behind reverse proxy (env: GF_BASE_PATH)

.PP
\fB--basic-user-password\fP=""
	Basic authentication password (env: GF_BASIC_AUTH_PASSWORD)

.PP
\fB--basic-user-username\fP=""
	Basic authentication username (env: GF_BASIC_AUTH_USERNAME)

.PP
\fB--debug\fP[=false]
	Enable debug logging (env: GF_DEBUG)

.PP
\fB--host\fP="localhost:3000"
	Grafana server host (env: GF_HOST)

.PP
\fB--org-id\fP=0
	Organization ID (env: GF_ORG_ID)

.PP
\fB--timeout\fP=30s
	Timeout for the HTTP request to the Grafana server; 0 disables it (env: GF_TIMEOUT)


.SH SEE ALSO
\fBgf-admin-ldap(1)\fP
