.nh
.TH "GF-CONVERT-PROMETHEUS" "1" "Jun 2026" "" ""

.SH NAME
gf-convert-prometheus - Convert prometheus API


.SH SYNOPSIS
\fBgf convert-prometheus [flags]\fP


.SH DESCRIPTION
Convert prometheus API


.SH OPTIONS
\fB-h\fP, \fB--help\fP[=false]
	help for convert-prometheus


.SH OPTIONS INHERITED FROM PARENT COMMANDS
\fB--api-key\fP=""
	API Key to authenticate to grafana server (env: GF_API_KEY)

.PP
\fB--base-path\fP="/api"
	Base path for server: useful when using sever behind reverse proxy (env: GF_BASE_PATH)

.PP
\fB--basic-user-password\fP=""
	Basic authentication password (env: GF_BASIC_AUTH_USERNAME)

.PP
\fB--basic-user-username\fP=""
	Basic authentication username (env: GF_BASIC_AUTH_PASSWORD)

.PP
\fB--debug\fP[=false]
	Enable debug logging (env: GF_DEBUG)

.PP
\fB--host\fP="localhost:3000"
	Grafana server host (env: GF_HOST)

.PP
\fB--org-id\fP=0
	Organization ID (env: GF_ORG_ID)


.SH SEE ALSO
\fBgf(1)\fP, \fBgf-convert-prometheus-convert-prometheus-cortex-delete-namespace(1)\fP, \fBgf-convert-prometheus-convert-prometheus-cortex-delete-rule-group(1)\fP, \fBgf-convert-prometheus-convert-prometheus-cortex-get-namespace(1)\fP, \fBgf-convert-prometheus-convert-prometheus-cortex-get-rule-group(1)\fP, \fBgf-convert-prometheus-convert-prometheus-cortex-get-rules(1)\fP, \fBgf-convert-prometheus-convert-prometheus-cortex-post-rule-group(1)\fP, \fBgf-convert-prometheus-convert-prometheus-cortex-post-rule-groups(1)\fP, \fBgf-convert-prometheus-convert-prometheus-delete-namespace(1)\fP, \fBgf-convert-prometheus-convert-prometheus-delete-rule-group(1)\fP, \fBgf-convert-prometheus-convert-prometheus-get-namespace(1)\fP, \fBgf-convert-prometheus-convert-prometheus-get-rule-group(1)\fP, \fBgf-convert-prometheus-convert-prometheus-get-rules(1)\fP, \fBgf-convert-prometheus-convert-prometheus-post-rule-group(1)\fP, \fBgf-convert-prometheus-convert-prometheus-post-rule-groups(1)\fP
