.nh
.TH "GF-CONVERT-PROMETHEUS-CONVERT-PROMETHEUS-CORTEX-GET-RULE-GROUP" "1" "May 2026" "" ""

.SH NAME
gf-convert-prometheus-convert-prometheus-cortex-get-rule-group - Gets a single rule group in prometheus compatible format if it was imported from a prometheus compatible source


.SH SYNOPSIS
\fBgf convert-prometheus convert-prometheus-cortex-get-rule-group [flags]\fP


.SH DESCRIPTION
Gets a single rule group in prometheus compatible format if it was imported from a prometheus compatible source

.PP
Response schema (ConvertPrometheusCortexGetRuleGroupOK.Payload):
  interval                 number
  labels                   map
  limit                    number
  name                     string
  query_offset             string
  rules                    array
  rules[].alert            string
  rules[].annotations      map
  rules[].expr             string
  rules[].for              string
  rules[].keep_firing_for  string
  rules[].labels           map
  rules[].record           string


.SH OPTIONS
\fB--describe-response-jsonschema\fP[=false]
	Print the JSON Schema of the response payload and exit without calling the API

.PP
\fB--group\fP=""
	Group

.PP
\fB-h\fP, \fB--help\fP[=false]
	help for convert-prometheus-cortex-get-rule-group

.PP
\fB--namespace-title\fP=""
	NamespaceTitle

.PP
\fB--raw\fP[=false]
	Print the raw HTTP response body instead of the decoded payload


.SH OPTIONS INHERITED FROM PARENT COMMANDS
\fB--api-key\fP=""
	API Key to authenticate to grafana server (env: GF_API_KEY)

.PP
\fB--base-path\fP="/api"
	Base path for server: useful when using sever behind reverse proxy (env: GF_BASE_PATH)

.PP
\fB--basic-user-password\fP=""
	Basic authentication password (env: GF_BASIC_AUTH_USERNAME)

.PP
\fB--basic-user-username\fP=""
	Basic authentication username (env: GF_BASIC_AUTH_PASSWORD)

.PP
\fB--debug\fP[=false]
	Enable debug logging (env: GF_DEBUG)

.PP
\fB--host\fP="localhost:3000"
	Grafana server host (env: GF_HOST)

.PP
\fB--org-id\fP=0
	Organization ID (env: GF_ORG_ID)


.SH SEE ALSO
\fBgf-convert-prometheus(1)\fP
