.nh
.TH "GF-DASHBOARDS-GET-DASHBOARD-VERSION-BY-UID" "1" "May 2026" "" ""

.SH NAME
gf-dashboards-get-dashboard-version-by-uid - Gets a specific dashboard version using UID


.SH SYNOPSIS
\fBgf dashboards get-dashboard-version-by-uid [flags]\fP


.SH DESCRIPTION
Gets a specific dashboard version using UID

.PP
Response schema (GetDashboardVersionByUIDOK.Payload):
  created        string
  createdBy      string
  dashboardId    number
  data           object
  id             number
  message        string
  parentVersion  number
  restoredFrom   number
  uid            string
  version        number


.SH OPTIONS
\fB--dashboard-version-id\fP=0
	DashboardVersionID

.PP
\fB--describe-response-jsonschema\fP[=false]
	Print the JSON Schema of the response payload and exit without calling the API

.PP
\fB-h\fP, \fB--help\fP[=false]
	help for get-dashboard-version-by-uid

.PP
\fB--raw\fP[=false]
	Print the raw HTTP response body instead of the decoded payload

.PP
\fB--uid\fP=""
	UID


.SH OPTIONS INHERITED FROM PARENT COMMANDS
\fB--api-key\fP=""
	API Key to authenticate to grafana server (env: GF_API_KEY)

.PP
\fB--base-path\fP="/api"
	Base path for server: useful when using sever behind reverse proxy (env: GF_BASE_PATH)

.PP
\fB--basic-user-password\fP=""
	Basic authentication password (env: GF_BASIC_AUTH_USERNAME)

.PP
\fB--basic-user-username\fP=""
	Basic authentication username (env: GF_BASIC_AUTH_PASSWORD)

.PP
\fB--debug\fP[=false]
	Enable debug logging (env: GF_DEBUG)

.PP
\fB--host\fP="localhost:3000"
	Grafana server host (env: GF_HOST)

.PP
\fB--org-id\fP=0
	Organization ID (env: GF_ORG_ID)


.SH SEE ALSO
\fBgf-dashboards(1)\fP
