.nh
.TH "GF-DATASOURCES" "1" "Jun 2026" "" ""

.SH NAME
gf-datasources - Datasources API


.SH SYNOPSIS
\fBgf datasources [flags]\fP


.SH DESCRIPTION
Datasources API


.SH OPTIONS
\fB-h\fP, \fB--help\fP[=false]
	help for datasources


.SH OPTIONS INHERITED FROM PARENT COMMANDS
\fB--api-key\fP=""
	API Key to authenticate to grafana server (env: GF_API_KEY)

.PP
\fB--base-path\fP="/api"
	Base path for server: useful when using server behind reverse proxy (env: GF_BASE_PATH)

.PP
\fB--basic-user-password\fP=""
	Basic authentication password (env: GF_BASIC_AUTH_PASSWORD)

.PP
\fB--basic-user-username\fP=""
	Basic authentication username (env: GF_BASIC_AUTH_USERNAME)

.PP
\fB--debug\fP[=false]
	Enable debug logging (env: GF_DEBUG)

.PP
\fB--host\fP="localhost:3000"
	Grafana server host (env: GF_HOST)

.PP
\fB--org-id\fP=0
	Organization ID (env: GF_ORG_ID)

.PP
\fB--timeout\fP=30s
	Timeout for the HTTP request to the Grafana server; 0 disables it (env: GF_TIMEOUT)


.SH SEE ALSO
\fBgf(1)\fP, \fBgf-datasources-add-datasource(1)\fP, \fBgf-datasources-call-datasource-resource(1)\fP, \fBgf-datasources-check-datasource-health(1)\fP, \fBgf-datasources-create-correlation(1)\fP, \fBgf-datasources-delete-correlation(1)\fP, \fBgf-datasources-delete-datasource-by-name(1)\fP, \fBgf-datasources-delete-datasource-by-uid(1)\fP, \fBgf-datasources-get-correlation(1)\fP, \fBgf-datasources-get-correlations(1)\fP, \fBgf-datasources-get-correlations-by-source-uid(1)\fP, \fBgf-datasources-get-datasource-by-name(1)\fP, \fBgf-datasources-get-datasource-by-uid(1)\fP, \fBgf-datasources-get-datasource-id-by-name(1)\fP, \fBgf-datasources-get-datasources(1)\fP, \fBgf-datasources-query-metrics-with-expressions(1)\fP, \fBgf-datasources-update-correlation(1)\fP, \fBgf-datasources-update-datasource-by-uid(1)\fP
