.nh
.TH "GF-DASHBOARDS-CREATE-DASHBOARD-SNAPSHOT" "1" "Apr 2026" "" ""

.SH NAME
gf-dashboards-create-dashboard-snapshot - Whens creating a snapshot using the API you have to provide the full dashboard payload including the snapshot data this endpoint is designed for the grafana UI


.SH SYNOPSIS
\fBgf dashboards create-dashboard-snapshot [flags]\fP


.SH DESCRIPTION
Whens creating a snapshot using the API you have to provide the full dashboard payload including the snapshot data this endpoint is designed for the grafana UI

.PP
Snapshot public mode should be enabled or authentication is required.

.PP
Body schema (CreateDashboardSnapshotCommand):
{
  "apiVersion": string,
  "dashboard": any,
  "deleteKey": string,
  "expires": number,
  "external": boolean,
  "key": string,
  "kind": string,
  "name": string
}
  apiVersion               APIVersion defines the versioned schema of this representation of an object. Servers should convert recognized schemas to the latest internal value, and may reject unrecognized values. More info: https://git.k8s.io/community/contributors/devel/sig-architecture/api-conventions.md#resources +optional
  dashboard                required
  deleteKey                Unique key used to delete the snapshot. It is different from the \fBkey\fR so that only the creator can delete the snapshot. Required if \fBexternal\fR is \fBtrue\fR\&.
  expires                  When the snapshot should expire in seconds in seconds. Default is never to expire.
  external                 these are passed when storing an external snapshot ref Save the snapshot on an external server rather than locally.
  key                      Define the unique key. Required if \fBexternal\fR is \fBtrue\fR\&.
  kind                     Kind is a string value representing the REST resource this object represents. Servers may infer this from the endpoint the client submits requests to. Cannot be updated. In CamelCase. More info: https://git.k8s.io/community/contributors/devel/sig-architecture/api-conventions.md#types-kinds +optional
  name                     Snapshot name


.SH OPTIONS
\fB--body\fP=""
	The path to the body json file or json string. For example, --body=/path/to/body.json or --body='{"foo": "bar"}'

.PP
\fB--describe-body-jsonschema\fP[=false]
	Print the JSON Schema of the request body and exit without calling the API

.PP
\fB-h\fP, \fB--help\fP[=false]
	help for create-dashboard-snapshot


.SH OPTIONS INHERITED FROM PARENT COMMANDS
\fB--api-key\fP=""
	API Key to authenticate to grafana server (env: GF_API_KEY)

.PP
\fB--base-path\fP="/api"
	Base path for server: useful when using sever behind reverse proxy (env: GF_BASE_PATH)

.PP
\fB--basic-user-password\fP=""
	Basic authentication password (env: GF_BASIC_AUTH_USERNAME)

.PP
\fB--basic-user-username\fP=""
	Basic authentication username (env: GF_BASIC_AUTH_PASSWORD)

.PP
\fB--debug\fP[=false]
	Enable debug logging (env: GF_DEBUG)

.PP
\fB--host\fP="localhost:3000"
	Grafana server host (env: GF_HOST)

.PP
\fB--org-id\fP=0
	Organization ID (env: GF_ORG_ID)


.SH SEE ALSO
\fBgf-dashboards(1)\fP
