.nh
.TH "GF-DATASOURCES-GET-CORRELATION" "1" "May 2026" "" ""

.SH NAME
gf-datasources-get-correlation - Gets a correlation


.SH SYNOPSIS
\fBgf datasources get-correlation [flags]\fP


.SH DESCRIPTION
Gets a correlation

.PP
Response schema (GetCorrelationOK.Payload):
  config                               object
  config.field                         string         REQUIRED
                                                      Field used to attach the correlation link
  config.target                        object         REQUIRED
                                                      Target data query
  config.transformations               array
  config.transformations[].expression  string
  config.transformations[].field       string
  config.transformations[].mapValue    string
  config.transformations[].type        string         enum: regex | logfmt
  config.type                          string
  description                          string         Description of the correlation
  label                                string         Label identifying the correlation
  orgId                                number         OrgID of the data source the correlation originates from
  provisioned                          boolean        Provisioned True if the correlation was created during provisioning
  sourceUID                            string         UID of the data source the correlation originates from
  targetUID                            string         UID of the data source the correlation points to
  type                                 string
  uid                                  string         Unique identifier of the correlation


.SH OPTIONS
\fB--correlation-uid\fP=""
	CorrelationUID

.PP
\fB--describe-response-jsonschema\fP[=false]
	Print the JSON Schema of the response payload and exit without calling the API

.PP
\fB-h\fP, \fB--help\fP[=false]
	help for get-correlation

.PP
\fB--raw\fP[=false]
	Print the raw HTTP response body instead of the decoded payload

.PP
\fB--source-uid\fP=""
	SourceUID


.SH OPTIONS INHERITED FROM PARENT COMMANDS
\fB--api-key\fP=""
	API Key to authenticate to grafana server (env: GF_API_KEY)

.PP
\fB--base-path\fP="/api"
	Base path for server: useful when using sever behind reverse proxy (env: GF_BASE_PATH)

.PP
\fB--basic-user-password\fP=""
	Basic authentication password (env: GF_BASIC_AUTH_USERNAME)

.PP
\fB--basic-user-username\fP=""
	Basic authentication username (env: GF_BASIC_AUTH_PASSWORD)

.PP
\fB--debug\fP[=false]
	Enable debug logging (env: GF_DEBUG)

.PP
\fB--host\fP="localhost:3000"
	Grafana server host (env: GF_HOST)

.PP
\fB--org-id\fP=0
	Organization ID (env: GF_ORG_ID)


.SH SEE ALSO
\fBgf-datasources(1)\fP
