.nh
.TH "GF-DASHBOARDS-GET-DASHBOARD-VERSIONS-BY-UID" "1" "Apr 2026" "" ""

.SH NAME
gf-dashboards-get-dashboard-versions-by-uid -


.SH SYNOPSIS
\fBgf dashboards get-dashboard-versions-by-uid [flags]\fP


.SH DESCRIPTION

.SH OPTIONS
\fB-h\fP, \fB--help\fP[=false]
	help for get-dashboard-versions-by-uid

.PP
\fB--limit\fP=0
	Maximum number of results to return

.PP
\fB--start\fP=0
	Version to start from when returning queries

.PP
\fB--uid\fP=""
	UID


.SH OPTIONS INHERITED FROM PARENT COMMANDS
\fB--api-key\fP=""
	API Key to authenticate to grafana server (env: GF_API_KEY)

.PP
\fB--base-path\fP="/api"
	Base path for server: useful when using sever behind reverse proxy (env: GF_BASE_PATH)

.PP
\fB--basic-user-password\fP=""
	Basic authentication password (env: GF_BASIC_AUTH_USERNAME)

.PP
\fB--basic-user-username\fP=""
	Basic authentication username (env: GF_BASIC_AUTH_PASSWORD)

.PP
\fB--debug\fP[=false]
	Enable debug logging (env: GF_DEBUG)

.PP
\fB--host\fP="localhost:3000"
	Grafana server host (env: GF_HOST)

.PP
\fB--org-id\fP=0
	Organization ID (env: GF_ORG_ID)


.SH SEE ALSO
\fBgf-dashboards(1)\fP
