.nh
.TH "GF-DASHBOARDS-RESTORE-DASHBOARD-VERSION-BY-UID" "1" "May 2026" "" ""

.SH NAME
gf-dashboards-restore-dashboard-version-by-uid - Restores a dashboard to a given dashboard version using UID


.SH SYNOPSIS
\fBgf dashboards restore-dashboard-version-by-uid [flags]\fP


.SH DESCRIPTION
Restores a dashboard to a given dashboard version using UID

.PP
This API will be removed when /apis/dashboards.grafana.app/v1 is released. You can restore a dashboard by reading it from history, then creating it again.

.PP
Body schema (RestoreDashboardVersionCommand):
  version  number

.PP
Response schema (RestoreDashboardVersionByUIDOK.Payload):
  folderUid  string  FolderUID The unique identifier (uid) of the folder the dashboard belongs to.
  id         number  REQUIRED
                     ID The unique identifier (id) of the created/updated dashboard.
  status     string  REQUIRED
                     Status status of the response.
  title      string  REQUIRED
                     Slug The slug of the dashboard.
  uid        string  REQUIRED
                     UID The unique identifier (uid) of the created/updated dashboard.
  url        string  REQUIRED
                     URL The relative URL for accessing the created/updated dashboard.
  version    number  REQUIRED
                     Version The version of the dashboard.


.SH OPTIONS
\fB--body\fP=""
	Request body JSON or path to a JSON file (e.g. --body=/path/to/body.json, --body='{"foo": "bar"}'). The 'Body schema' block above lists fields and types; use --describe-body-jsonschema for a strict JSON Schema.

.PP
\fB--describe-body-jsonschema\fP[=false]
	Print the JSON Schema of the request body and exit without calling the API

.PP
\fB--describe-response-jsonschema\fP[=false]
	Print the JSON Schema of the response payload and exit without calling the API

.PP
\fB-h\fP, \fB--help\fP[=false]
	help for restore-dashboard-version-by-uid

.PP
\fB--raw\fP[=false]
	Print the raw HTTP response body instead of the decoded payload

.PP
\fB--uid\fP=""
	UID


.SH OPTIONS INHERITED FROM PARENT COMMANDS
\fB--api-key\fP=""
	API Key to authenticate to grafana server (env: GF_API_KEY)

.PP
\fB--base-path\fP="/api"
	Base path for server: useful when using sever behind reverse proxy (env: GF_BASE_PATH)

.PP
\fB--basic-user-password\fP=""
	Basic authentication password (env: GF_BASIC_AUTH_USERNAME)

.PP
\fB--basic-user-username\fP=""
	Basic authentication username (env: GF_BASIC_AUTH_PASSWORD)

.PP
\fB--debug\fP[=false]
	Enable debug logging (env: GF_DEBUG)

.PP
\fB--host\fP="localhost:3000"
	Grafana server host (env: GF_HOST)

.PP
\fB--org-id\fP=0
	Organization ID (env: GF_ORG_ID)


.SH SEE ALSO
\fBgf-dashboards(1)\fP
