.nh
.TH "GF-DASHBOARDS-CREATE-DASHBOARD-SNAPSHOT" "1" "Apr 2026" "" ""

.SH NAME
gf-dashboards-create-dashboard-snapshot - Whens creating a snapshot using the API you have to provide the full dashboard payload including the snapshot data this endpoint is designed for the grafana UI


.SH SYNOPSIS
\fBgf dashboards create-dashboard-snapshot [flags]\fP


.SH DESCRIPTION
Whens creating a snapshot using the API you have to provide the full dashboard payload including the snapshot data this endpoint is designed for the grafana UI

.PP
Snapshot public mode should be enabled or authentication is required.

.PP
Body schema (CreateDashboardSnapshotCommand):
{
  "apiVersion": string,
  "dashboard": any,
  "deleteKey": string,
  "expires": number,
  "external": boolean,
  "key": string,
  "kind": string,
  "name": string
}
  dashboard                required


.SH OPTIONS
\fB--body\fP=""
	The path to the body json file or json string. For example, --body=/path/to/body.json or --body='{"foo": "bar"}'

.PP
\fB-h\fP, \fB--help\fP[=false]
	help for create-dashboard-snapshot


.SH OPTIONS INHERITED FROM PARENT COMMANDS
\fB--api-key\fP=""
	API Key to authenticate to grafana server (env: GF_API_KEY)

.PP
\fB--base-path\fP="/api"
	Base path for server: useful when using sever behind reverse proxy (env: GF_BASE_PATH)

.PP
\fB--basic-user-password\fP=""
	Basic authentication password (env: GF_BASIC_AUTH_USERNAME)

.PP
\fB--basic-user-username\fP=""
	Basic authentication username (env: GF_BASIC_AUTH_PASSWORD)

.PP
\fB--debug\fP[=false]
	Enable debug logging (env: GF_DEBUG)

.PP
\fB--host\fP="localhost:3000"
	Grafana server host (env: GF_HOST)

.PP
\fB--org-id\fP=0
	Organization ID (env: GF_ORG_ID)


.SH SEE ALSO
\fBgf-dashboards(1)\fP
