.nh
.TH "GF-DASHBOARDS-GET-DASHBOARD-VERSIONS-BY-UID" "1" "Jun 2026" "" ""

.SH NAME
gf-dashboards-get-dashboard-versions-by-uid - Gets all existing versions for the dashboard using UID


.SH SYNOPSIS
\fBgf dashboards get-dashboard-versions-by-uid [flags]\fP


.SH DESCRIPTION
Gets all existing versions for the dashboard using UID

.PP
Response schema (GetDashboardVersionsByUIDOK.Payload):
  continueToken             string
  versions                  array
  versions[].created        string
  versions[].createdBy      string
  versions[].dashboardId    number
  versions[].data           object
  versions[].id             number
  versions[].message        string
  versions[].parentVersion  number
  versions[].restoredFrom   number
  versions[].uid            string
  versions[].version        number


.SH OPTIONS
\fB--describe-response-jsonschema\fP[=false]
	Print the JSON Schema of the response payload and exit without calling the API

.PP
\fB-h\fP, \fB--help\fP[=false]
	help for get-dashboard-versions-by-uid

.PP
\fB--limit\fP=0
	Maximum number of results to return

.PP
\fB--raw\fP[=false]
	Print the raw HTTP response body instead of the decoded payload

.PP
\fB--start\fP=0
	Version to start from when returning queries

.PP
\fB--uid\fP=""
	UID [required]


.SH OPTIONS INHERITED FROM PARENT COMMANDS
\fB--api-key\fP=""
	API Key to authenticate to grafana server (env: GF_API_KEY)

.PP
\fB--base-path\fP="/api"
	Base path for server: useful when using server behind reverse proxy (env: GF_BASE_PATH)

.PP
\fB--basic-user-password\fP=""
	Basic authentication password (env: GF_BASIC_AUTH_PASSWORD)

.PP
\fB--basic-user-username\fP=""
	Basic authentication username (env: GF_BASIC_AUTH_USERNAME)

.PP
\fB--debug\fP[=false]
	Enable debug logging (env: GF_DEBUG)

.PP
\fB--host\fP="localhost:3000"
	Grafana server host (env: GF_HOST)

.PP
\fB--org-id\fP=0
	Organization ID (env: GF_ORG_ID)

.PP
\fB--timeout\fP=30s
	Timeout for the HTTP request to the Grafana server; 0 disables it (env: GF_TIMEOUT)


.SH SEE ALSO
\fBgf-dashboards(1)\fP
