.nh
.TH "GF-DASHBOARDS-GET-HOME-DASHBOARD" "1" "Jun 2026" "" ""

.SH NAME
gf-dashboards-get-home-dashboard - NOTE: the home dashboard is configured in preferences.


.SH SYNOPSIS
\fBgf dashboards get-home-dashboard [flags]\fP


.SH DESCRIPTION
NOTE: the home dashboard is configured in preferences.

.PP
This API will be removed in G13

.PP
Response schema (GetHomeDashboardOK.Payload):
  dashboard                                        object
  meta                                             object
  meta.annotationsPermissions                      object
  meta.annotationsPermissions.dashboard            object
  meta.annotationsPermissions.dashboard.canAdd     boolean
  meta.annotationsPermissions.dashboard.canDelete  boolean
  meta.annotationsPermissions.dashboard.canEdit    boolean
  meta.apiVersion                                  string
  meta.canAdmin                                    boolean
  meta.canDelete                                   boolean
  meta.canEdit                                     boolean
  meta.canSave                                     boolean
  meta.canStar                                     boolean
  meta.created                                     string
  meta.createdBy                                   string
  meta.expires                                     string
  meta.folderId                                    number   Deprecated: use FolderUID instead
  meta.folderTitle                                 string
  meta.folderUid                                   string
  meta.folderUrl                                   string
  meta.hasAcl                                      boolean
  meta.isFolder                                    boolean
  meta.isSnapshot                                  boolean
  meta.isStarred                                   boolean
  meta.provisioned                                 boolean
  meta.provisionedExternalId                       string
  meta.publicDashboardEnabled                      boolean
  meta.slug                                        string
  meta.type                                        string
  meta.updated                                     string
  meta.updatedBy                                   string
  meta.url                                         string
  meta.version                                     number
  redirectUri                                      string


.SH OPTIONS
\fB--describe-response-jsonschema\fP[=false]
	Print the JSON Schema of the response payload and exit without calling the API

.PP
\fB-h\fP, \fB--help\fP[=false]
	help for get-home-dashboard

.PP
\fB--raw\fP[=false]
	Print the raw HTTP response body instead of the decoded payload


.SH OPTIONS INHERITED FROM PARENT COMMANDS
\fB--api-key\fP=""
	API Key to authenticate to grafana server (env: GF_API_KEY)

.PP
\fB--base-path\fP="/api"
	Base path for server: useful when using sever behind reverse proxy (env: GF_BASE_PATH)

.PP
\fB--basic-user-password\fP=""
	Basic authentication password (env: GF_BASIC_AUTH_USERNAME)

.PP
\fB--basic-user-username\fP=""
	Basic authentication username (env: GF_BASIC_AUTH_PASSWORD)

.PP
\fB--debug\fP[=false]
	Enable debug logging (env: GF_DEBUG)

.PP
\fB--host\fP="localhost:3000"
	Grafana server host (env: GF_HOST)

.PP
\fB--org-id\fP=0
	Organization ID (env: GF_ORG_ID)


.SH SEE ALSO
\fBgf-dashboards(1)\fP
