.nh
.TH "GF-DATASOURCES-GET-DATASOURCE-BY-UID" "1" "Apr 2026" "" ""

.SH NAME
gf-datasources-get-datasource-by-uid - Gets a single data source by UID


.SH SYNOPSIS
\fBgf datasources get-datasource-by-uid [flags]\fP


.SH DESCRIPTION
Gets a single data source by UID

.PP
If you are running Grafana Enterprise and have Fine-grained access control enabled you need to have a permission with action: \fBdatasources:read\fR and scopes: \fBdatasources:*\fR, \fBdatasources:uid:*\fR and \fBdatasources:uid:kLtEtcRGk\fR (single data source).


.SH OPTIONS
\fB-h\fP, \fB--help\fP[=false]
	help for get-datasource-by-uid

.PP
\fB--raw\fP[=false]
	Print the raw HTTP response body instead of the decoded payload

.PP
\fB--uid\fP=""
	UID


.SH OPTIONS INHERITED FROM PARENT COMMANDS
\fB--api-key\fP=""
	API Key to authenticate to grafana server (env: GF_API_KEY)

.PP
\fB--base-path\fP="/api"
	Base path for server: useful when using sever behind reverse proxy (env: GF_BASE_PATH)

.PP
\fB--basic-user-password\fP=""
	Basic authentication password (env: GF_BASIC_AUTH_USERNAME)

.PP
\fB--basic-user-username\fP=""
	Basic authentication username (env: GF_BASIC_AUTH_PASSWORD)

.PP
\fB--debug\fP[=false]
	Enable debug logging (env: GF_DEBUG)

.PP
\fB--host\fP="localhost:3000"
	Grafana server host (env: GF_HOST)

.PP
\fB--org-id\fP=0
	Organization ID (env: GF_ORG_ID)


.SH SEE ALSO
\fBgf-datasources(1)\fP
