.nh
.TH "GF-FOLDERS-GET-FOLDER-DESCENDANT-COUNTS" "1" "May 2026" "" ""

.SH NAME
gf-folders-get-folder-descendant-counts - Gets the count of each descendant of a folder by kind the folder is identified by UID


.SH SYNOPSIS
\fBgf folders get-folder-descendant-counts [flags]\fP


.SH DESCRIPTION
Gets the count of each descendant of a folder by kind the folder is identified by UID

.PP
Use: /apis/folder.grafana.app/v1/namespaces/{ns}/folders/{folder_uid}


.SH OPTIONS
\fB--describe-response-jsonschema\fP[=false]
	Print the JSON Schema of the response payload and exit without calling the API

.PP
\fB--folder-uid\fP=""
	FolderUID

.PP
\fB-h\fP, \fB--help\fP[=false]
	help for get-folder-descendant-counts

.PP
\fB--raw\fP[=false]
	Print the raw HTTP response body instead of the decoded payload


.SH OPTIONS INHERITED FROM PARENT COMMANDS
\fB--api-key\fP=""
	API Key to authenticate to grafana server (env: GF_API_KEY)

.PP
\fB--base-path\fP="/api"
	Base path for server: useful when using sever behind reverse proxy (env: GF_BASE_PATH)

.PP
\fB--basic-user-password\fP=""
	Basic authentication password (env: GF_BASIC_AUTH_USERNAME)

.PP
\fB--basic-user-username\fP=""
	Basic authentication username (env: GF_BASIC_AUTH_PASSWORD)

.PP
\fB--debug\fP[=false]
	Enable debug logging (env: GF_DEBUG)

.PP
\fB--host\fP="localhost:3000"
	Grafana server host (env: GF_HOST)

.PP
\fB--org-id\fP=0
	Organization ID (env: GF_ORG_ID)


.SH SEE ALSO
\fBgf-folders(1)\fP
