.nh
.TH "GF-LIBRARY-ELEMENTS-GET-LIBRARY-ELEMENT-BY-NAME" "1" "May 2026" "" ""

.SH NAME
gf-library-elements-get-library-element-by-name - Gets library element by name


.SH SYNOPSIS
\fBgf library-elements get-library-element-by-name [flags]\fP


.SH DESCRIPTION
Gets library element by name

.PP
Returns a library element with the given name.

.PP
Response schema (GetLibraryElementByNameOK.Payload):
  result                             array
  result[].description               string
  result[].folderId                  number         Deprecated: use FolderUID instead
  result[].folderUid                 string
  result[].id                        number
  result[].kind                      number
  result[].meta                      object
  result[].meta.connectedDashboards  number
  result[].meta.created              string
  result[].meta.createdBy            object
  result[].meta.createdBy.avatarUrl  string
  result[].meta.createdBy.id         number
  result[].meta.createdBy.name       string
  result[].meta.folderName           string
  result[].meta.folderUid            string
  result[].meta.updated              string
  result[].meta.updatedBy            object
  result[].meta.updatedBy.avatarUrl  string
  result[].meta.updatedBy.id         number
  result[].meta.updatedBy.name       string
  result[].model                     object
  result[].name                      string
  result[].orgId                     number
  result[].schemaVersion             number
  result[].type                      string
  result[].uid                       string
  result[].version                   number


.SH OPTIONS
\fB--describe-response-jsonschema\fP[=false]
	Print the JSON Schema of the response payload and exit without calling the API

.PP
\fB-h\fP, \fB--help\fP[=false]
	help for get-library-element-by-name

.PP
\fB--library-element-name\fP=""
	LibraryElementName [required]

.PP
\fB--raw\fP[=false]
	Print the raw HTTP response body instead of the decoded payload


.SH OPTIONS INHERITED FROM PARENT COMMANDS
\fB--api-key\fP=""
	API Key to authenticate to grafana server (env: GF_API_KEY)

.PP
\fB--base-path\fP="/api"
	Base path for server: useful when using sever behind reverse proxy (env: GF_BASE_PATH)

.PP
\fB--basic-user-password\fP=""
	Basic authentication password (env: GF_BASIC_AUTH_USERNAME)

.PP
\fB--basic-user-username\fP=""
	Basic authentication username (env: GF_BASIC_AUTH_PASSWORD)

.PP
\fB--debug\fP[=false]
	Enable debug logging (env: GF_DEBUG)

.PP
\fB--host\fP="localhost:3000"
	Grafana server host (env: GF_HOST)

.PP
\fB--org-id\fP=0
	Organization ID (env: GF_ORG_ID)


.SH SEE ALSO
\fBgf-library-elements(1)\fP
