.nh
.TH "GF-LIBRARY-ELEMENTS-GET-LIBRARY-ELEMENTS" "1" "May 2026" "" ""

.SH NAME
gf-library-elements-get-library-elements - Gets all library elements


.SH SYNOPSIS
\fBgf library-elements get-library-elements [flags]\fP


.SH DESCRIPTION
Gets all library elements

.PP
Returns a list of all library elements the authenticated user has permission to view. Use the \fBperPage\fR query parameter to control the maximum number of library elements returned; the default limit is \fB100\fR\&. You can also use the \fBpage\fR query parameter to fetch library elements from any page other than the first one.

.PP
Response schema (GetLibraryElementsOK.Payload):
  result                                      object
  result.elements                             array
  result.elements[].description               string
  result.elements[].folderId                  number         Deprecated: use FolderUID instead
  result.elements[].folderUid                 string
  result.elements[].id                        number
  result.elements[].kind                      number
  result.elements[].meta                      object
  result.elements[].meta.connectedDashboards  number
  result.elements[].meta.created              string
  result.elements[].meta.createdBy            object
  result.elements[].meta.createdBy.avatarUrl  string
  result.elements[].meta.createdBy.id         number
  result.elements[].meta.createdBy.name       string
  result.elements[].meta.folderName           string
  result.elements[].meta.folderUid            string
  result.elements[].meta.updated              string
  result.elements[].meta.updatedBy            object
  result.elements[].meta.updatedBy.avatarUrl  string
  result.elements[].meta.updatedBy.id         number
  result.elements[].meta.updatedBy.name       string
  result.elements[].model                     object
  result.elements[].name                      string
  result.elements[].orgId                     number
  result.elements[].schemaVersion             number
  result.elements[].type                      string
  result.elements[].uid                       string
  result.elements[].version                   number
  result.page                                 number
  result.perPage                              number
  result.totalCount                           number


.SH OPTIONS
\fB--describe-response-jsonschema\fP[=false]
	Print the JSON Schema of the response payload and exit without calling the API

.PP
\fB--exclude-uid\fP=""
	Element UID to exclude from search results.

.PP
\fB--folder-filter\fP=""
	A comma separated list of folder ID(s) to filter the elements by. Deprecated: Use FolderFilterUIDs instead.

.PP
\fB--folder-filter-uids\fP=""
	A comma separated list of folder UID(s) to filter the elements by.

.PP
\fB-h\fP, \fB--help\fP[=false]
	help for get-library-elements

.PP
\fB--kind\fP=0
	Kind of element to search for.

.PP
\fB--page\fP=1
	The page for a set of records, given that only perPage records are returned at a time. Numbering starts at 1.

.PP
\fB--per-page\fP=100
	The number of results per page.

.PP
\fB--raw\fP[=false]
	Print the raw HTTP response body instead of the decoded payload

.PP
\fB--search-string\fP=""
	Part of the name or description searched for.

.PP
\fB--sort-direction\fP=""
	Sort order of elements.

.PP
\fB--type-filter\fP=""
	A comma separated list of types to filter the elements by


.SH OPTIONS INHERITED FROM PARENT COMMANDS
\fB--api-key\fP=""
	API Key to authenticate to grafana server (env: GF_API_KEY)

.PP
\fB--base-path\fP="/api"
	Base path for server: useful when using sever behind reverse proxy (env: GF_BASE_PATH)

.PP
\fB--basic-user-password\fP=""
	Basic authentication password (env: GF_BASIC_AUTH_USERNAME)

.PP
\fB--basic-user-username\fP=""
	Basic authentication username (env: GF_BASIC_AUTH_PASSWORD)

.PP
\fB--debug\fP[=false]
	Enable debug logging (env: GF_DEBUG)

.PP
\fB--host\fP="localhost:3000"
	Grafana server host (env: GF_HOST)

.PP
\fB--org-id\fP=0
	Organization ID (env: GF_ORG_ID)


.SH SEE ALSO
\fBgf-library-elements(1)\fP
