.nh
.TH "GF-LIBRARY-ELEMENTS-GET-LIBRARY-ELEMENTS" "1" "Apr 2026" "" ""

.SH NAME
gf-library-elements-get-library-elements -


.SH SYNOPSIS
\fBgf library-elements get-library-elements [flags]\fP


.SH DESCRIPTION

.SH OPTIONS
\fB--exclude-uid\fP=""
	Element UID to exclude from search results.

.PP
\fB--folder-filter\fP=""
	A comma separated list of folder ID(s) to filter the elements by.

.PP
\fB-h\fP, \fB--help\fP[=false]
	help for get-library-elements

.PP
\fB--kind\fP=0
	Kind of element to search for.

.PP
\fB--page\fP=0
	The page for a set of records, given that only perPage records are returned at a time. Numbering starts at 1. Default: 1

.PP
\fB--per-page\fP=0
	The number of results per page. Default: 100

.PP
\fB--raw\fP[=false]
	Print the raw HTTP response body instead of the decoded payload

.PP
\fB--search-string\fP=""
	Part of the name or description searched for.

.PP
\fB--sort-direction\fP=""
	Sort order of elements.

.PP
\fB--type-filter\fP=""
	A comma separated list of types to filter the elements by


.SH OPTIONS INHERITED FROM PARENT COMMANDS
\fB--api-key\fP=""
	API Key to authenticate to grafana server (env: GF_API_KEY)

.PP
\fB--base-path\fP="/api"
	Base path for server: useful when using sever behind reverse proxy (env: GF_BASE_PATH)

.PP
\fB--basic-user-password\fP=""
	Basic authentication password (env: GF_BASIC_AUTH_USERNAME)

.PP
\fB--basic-user-username\fP=""
	Basic authentication username (env: GF_BASIC_AUTH_PASSWORD)

.PP
\fB--debug\fP[=false]
	Enable debug logging (env: GF_DEBUG)

.PP
\fB--host\fP="localhost:3000"
	Grafana server host (env: GF_HOST)

.PP
\fB--org-id\fP=0
	Organization ID (env: GF_ORG_ID)


.SH SEE ALSO
\fBgf-library-elements(1)\fP
