.nh
.TH "GF-MIGRATIONS" "1" "May 2026" "" ""

.SH NAME
gf-migrations - Migrations API


.SH SYNOPSIS
\fBgf migrations [flags]\fP


.SH DESCRIPTION
Migrations API


.SH OPTIONS
\fB-h\fP, \fB--help\fP[=false]
	help for migrations


.SH OPTIONS INHERITED FROM PARENT COMMANDS
\fB--api-key\fP=""
	API Key to authenticate to grafana server (env: GF_API_KEY)

.PP
\fB--base-path\fP="/api"
	Base path for server: useful when using sever behind reverse proxy (env: GF_BASE_PATH)

.PP
\fB--basic-user-password\fP=""
	Basic authentication password (env: GF_BASIC_AUTH_USERNAME)

.PP
\fB--basic-user-username\fP=""
	Basic authentication username (env: GF_BASIC_AUTH_PASSWORD)

.PP
\fB--debug\fP[=false]
	Enable debug logging (env: GF_DEBUG)

.PP
\fB--host\fP="localhost:3000"
	Grafana server host (env: GF_HOST)

.PP
\fB--org-id\fP=0
	Organization ID (env: GF_ORG_ID)


.SH SEE ALSO
\fBgf(1)\fP, \fBgf-migrations-cancel-snapshot(1)\fP, \fBgf-migrations-create-cloud-migration-token(1)\fP, \fBgf-migrations-create-session(1)\fP, \fBgf-migrations-create-snapshot(1)\fP, \fBgf-migrations-delete-cloud-migration-token(1)\fP, \fBgf-migrations-delete-session(1)\fP, \fBgf-migrations-get-cloud-migration-token(1)\fP, \fBgf-migrations-get-resource-dependencies(1)\fP, \fBgf-migrations-get-session(1)\fP, \fBgf-migrations-get-session-list(1)\fP, \fBgf-migrations-get-shapshot-list(1)\fP, \fBgf-migrations-get-snapshot(1)\fP, \fBgf-migrations-upload-snapshot(1)\fP
