.nh
.TH "GF-ORGS" "1" "May 2026" "" ""

.SH NAME
gf-orgs - Orgs API


.SH SYNOPSIS
\fBgf orgs [flags]\fP


.SH DESCRIPTION
Orgs API


.SH OPTIONS
\fB-h\fP, \fB--help\fP[=false]
	help for orgs


.SH OPTIONS INHERITED FROM PARENT COMMANDS
\fB--api-key\fP=""
	API Key to authenticate to grafana server (env: GF_API_KEY)

.PP
\fB--base-path\fP="/api"
	Base path for server: useful when using sever behind reverse proxy (env: GF_BASE_PATH)

.PP
\fB--basic-user-password\fP=""
	Basic authentication password (env: GF_BASIC_AUTH_USERNAME)

.PP
\fB--basic-user-username\fP=""
	Basic authentication username (env: GF_BASIC_AUTH_PASSWORD)

.PP
\fB--debug\fP[=false]
	Enable debug logging (env: GF_DEBUG)

.PP
\fB--host\fP="localhost:3000"
	Grafana server host (env: GF_HOST)

.PP
\fB--org-id\fP=0
	Organization ID (env: GF_ORG_ID)


.SH SEE ALSO
\fBgf(1)\fP, \fBgf-orgs-add-org-user(1)\fP, \fBgf-orgs-create-org(1)\fP, \fBgf-orgs-get-org-by-name(1)\fP, \fBgf-orgs-get-org-users(1)\fP, \fBgf-orgs-remove-org-user(1)\fP, \fBgf-orgs-search-org-users(1)\fP, \fBgf-orgs-search-orgs(1)\fP, \fBgf-orgs-update-org(1)\fP, \fBgf-orgs-update-org-address(1)\fP, \fBgf-orgs-update-org-user(1)\fP
