.nh
.TH "GF-ORGS-SEARCH-ORG-USERS" "1" "Jun 2026" "" ""

.SH NAME
gf-orgs-search-org-users - Searches users in organization


.SH SYNOPSIS
\fBgf orgs search-org-users [flags]\fP


.SH DESCRIPTION
Searches users in organization

.PP
If you are running Grafana Enterprise and have Fine-grained access control enabled you need to have a permission with action: \fBorg.users:read\fR with scope \fBusers:*\fR\&.

.PP
Response schema (SearchOrgUsersOK.Payload):
  orgUsers                       array
  orgUsers[].accessControl       map
  orgUsers[].authLabels          array
  orgUsers[].avatarUrl           string
  orgUsers[].created             string
  orgUsers[].email               string
  orgUsers[].isDisabled          boolean
  orgUsers[].isExternallySynced  boolean
  orgUsers[].isProvisioned       boolean
  orgUsers[].lastSeenAt          string
  orgUsers[].lastSeenAtAge       string
  orgUsers[].login               string
  orgUsers[].name                string
  orgUsers[].orgId               number
  orgUsers[].role                string
  orgUsers[].uid                 string
  orgUsers[].userId              number
  page                           number
  perPage                        number
  totalCount                     number


.SH OPTIONS
\fB--describe-response-jsonschema\fP[=false]
	Print the JSON Schema of the response payload and exit without calling the API

.PP
\fB-h\fP, \fB--help\fP[=false]
	help for search-org-users

.PP
\fB--org-id\fP=0
	OrgID [required]

.PP
\fB--raw\fP[=false]
	Print the raw HTTP response body instead of the decoded payload


.SH OPTIONS INHERITED FROM PARENT COMMANDS
\fB--api-key\fP=""
	API Key to authenticate to grafana server (env: GF_API_KEY)

.PP
\fB--base-path\fP="/api"
	Base path for server: useful when using server behind reverse proxy (env: GF_BASE_PATH)

.PP
\fB--basic-user-password\fP=""
	Basic authentication password (env: GF_BASIC_AUTH_PASSWORD)

.PP
\fB--basic-user-username\fP=""
	Basic authentication username (env: GF_BASIC_AUTH_USERNAME)

.PP
\fB--debug\fP[=false]
	Enable debug logging (env: GF_DEBUG)

.PP
\fB--host\fP="localhost:3000"
	Grafana server host (env: GF_HOST)

.PP
\fB--timeout\fP=30s
	Timeout for the HTTP request to the Grafana server; 0 disables it (env: GF_TIMEOUT)


.SH SEE ALSO
\fBgf-orgs(1)\fP
