.nh
.TH "GF-ORG-REMOVE-ORG-USER-FOR-CURRENT-ORG" "1" "Jun 2026" "" ""

.SH NAME
gf-org-remove-org-user-for-current-org - Deletes user in current organization


.SH SYNOPSIS
\fBgf org remove-org-user-for-current-org [flags]\fP


.SH DESCRIPTION
Deletes user in current organization

.PP
If you are running Grafana Enterprise and have Fine-grained access control enabled you need to have a permission with action: \fBorg.users:remove\fR with scope \fBusers:*\fR\&.

.PP
Response schema (RemoveOrgUserForCurrentOrgOK.Payload):
  message  string


.SH OPTIONS
\fB--describe-response-jsonschema\fP[=false]
	Print the JSON Schema of the response payload and exit without calling the API

.PP
\fB-h\fP, \fB--help\fP[=false]
	help for remove-org-user-for-current-org

.PP
\fB--raw\fP[=false]
	Print the raw HTTP response body instead of the decoded payload

.PP
\fB--user-id\fP=0
	UserID [required]


.SH OPTIONS INHERITED FROM PARENT COMMANDS
\fB--api-key\fP=""
	API Key to authenticate to grafana server (env: GF_API_KEY)

.PP
\fB--base-path\fP="/api"
	Base path for server: useful when using server behind reverse proxy (env: GF_BASE_PATH)

.PP
\fB--basic-user-password\fP=""
	Basic authentication password (env: GF_BASIC_AUTH_PASSWORD)

.PP
\fB--basic-user-username\fP=""
	Basic authentication username (env: GF_BASIC_AUTH_USERNAME)

.PP
\fB--debug\fP[=false]
	Enable debug logging (env: GF_DEBUG)

.PP
\fB--host\fP="localhost:3000"
	Grafana server host (env: GF_HOST)

.PP
\fB--org-id\fP=0
	Organization ID (env: GF_ORG_ID)

.PP
\fB--timeout\fP=30s
	Timeout for the HTTP request to the Grafana server; 0 disables it (env: GF_TIMEOUT)


.SH SEE ALSO
\fBgf-org(1)\fP
