.nh
.TH "GF-ORG" "1" "Apr 2026" "" ""

.SH NAME
gf-org - Org API


.SH SYNOPSIS
\fBgf org [flags]\fP


.SH DESCRIPTION
Org API


.SH OPTIONS
\fB-h\fP, \fB--help\fP[=false]
	help for org


.SH OPTIONS INHERITED FROM PARENT COMMANDS
\fB--api-key\fP=""
	API Key to authenticate to grafana server (env: GF_API_KEY)

.PP
\fB--base-path\fP="/api"
	Base path for server: useful when using sever behind reverse proxy (env: GF_BASE_PATH)

.PP
\fB--basic-user-password\fP=""
	Basic authentication password (env: GF_BASIC_AUTH_USERNAME)

.PP
\fB--basic-user-username\fP=""
	Basic authentication username (env: GF_BASIC_AUTH_PASSWORD)

.PP
\fB--debug\fP[=false]
	Enable debug logging (env: GF_DEBUG)

.PP
\fB--host\fP="localhost:3000"
	Grafana server host (env: GF_HOST)

.PP
\fB--org-id\fP=0
	Organization ID (env: GF_ORG_ID)


.SH SEE ALSO
\fBgf(1)\fP, \fBgf-org-add-org-invite(1)\fP, \fBgf-org-add-org-user-to-current-org(1)\fP, \fBgf-org-get-current-org(1)\fP, \fBgf-org-get-org-preferences(1)\fP, \fBgf-org-get-org-users-for-current-org(1)\fP, \fBgf-org-get-org-users-for-current-org-lookup(1)\fP, \fBgf-org-get-pending-org-invites(1)\fP, \fBgf-org-patch-org-preferences(1)\fP, \fBgf-org-remove-org-user-for-current-org(1)\fP, \fBgf-org-revoke-invite(1)\fP, \fBgf-org-update-current-org(1)\fP, \fBgf-org-update-current-org-address(1)\fP, \fBgf-org-update-org-preferences(1)\fP, \fBgf-org-update-org-user-for-current-org(1)\fP
