.nh
.TH "GF-ORGS-SEARCH-ORGS" "1" "Jun 2026" "" ""

.SH NAME
gf-orgs-search-orgs - Searches all organizations


.SH SYNOPSIS
\fBgf orgs search-orgs [flags]\fP


.SH DESCRIPTION
Searches all organizations


.SH OPTIONS
\fB--describe-response-jsonschema\fP[=false]
	Print the JSON Schema of the response payload and exit without calling the API

.PP
\fB-h\fP, \fB--help\fP[=false]
	help for search-orgs

.PP
\fB--name\fP=""
	Name

.PP
\fB--page\fP=1
	Page

.PP
\fB--perpage\fP=1000
	Number of items per page The totalCount field in the response can be used for pagination list E.g. if totalCount is equal to 100 teams and the perpage parameter is set to 10 then there are 10 pages of teams.

.PP
\fB--query\fP=""
	If set it will return results where the query value is contained in the name field. Query values with spaces need to be URL encoded.

.PP
\fB--raw\fP[=false]
	Print the raw HTTP response body instead of the decoded payload


.SH OPTIONS INHERITED FROM PARENT COMMANDS
\fB--api-key\fP=""
	API Key to authenticate to grafana server (env: GF_API_KEY)

.PP
\fB--base-path\fP="/api"
	Base path for server: useful when using sever behind reverse proxy (env: GF_BASE_PATH)

.PP
\fB--basic-user-password\fP=""
	Basic authentication password (env: GF_BASIC_AUTH_USERNAME)

.PP
\fB--basic-user-username\fP=""
	Basic authentication username (env: GF_BASIC_AUTH_PASSWORD)

.PP
\fB--debug\fP[=false]
	Enable debug logging (env: GF_DEBUG)

.PP
\fB--host\fP="localhost:3000"
	Grafana server host (env: GF_HOST)

.PP
\fB--org-id\fP=0
	Organization ID (env: GF_ORG_ID)


.SH SEE ALSO
\fBgf-orgs(1)\fP
