.nh
.TH "GF-PROVISIONING-GET-ALERT-RULES-EXPORT" "1" "Apr 2026" "" ""

.SH NAME
gf-provisioning-get-alert-rules-export -


.SH SYNOPSIS
\fBgf provisioning get-alert-rules-export [flags]\fP


.SH DESCRIPTION

.SH OPTIONS
\fB--download\fP[=false]
	Whether to initiate a download of the file or not.

.PP
\fB--folder-uid\fP=[]
	UIDs of folders from which to export rules

.PP
\fB--format\fP=""
	Format of the downloaded file. Supported yaml, json or hcl. Accept header can also be used, but the query parameter will take precedence. Default: "yaml"

.PP
\fB--group\fP=""
	Name of group of rules to export. Must be specified only together with a single folder UID

.PP
\fB-h\fP, \fB--help\fP[=false]
	help for get-alert-rules-export

.PP
\fB--rule-uid\fP=""
	UID of alert rule to export. If specified, parameters folderUid and group must be empty.


.SH OPTIONS INHERITED FROM PARENT COMMANDS
\fB--api-key\fP=""
	API Key to authenticate to grafana server (env: GF_API_KEY)

.PP
\fB--base-path\fP="/api"
	Base path for server: useful when using sever behind reverse proxy (env: GF_BASE_PATH)

.PP
\fB--basic-user-password\fP=""
	Basic authentication password (env: GF_BASIC_AUTH_USERNAME)

.PP
\fB--basic-user-username\fP=""
	Basic authentication username (env: GF_BASIC_AUTH_PASSWORD)

.PP
\fB--debug\fP[=false]
	Enable debug logging (env: GF_DEBUG)

.PP
\fB--host\fP="localhost:3000"
	Grafana server host (env: GF_HOST)

.PP
\fB--org-id\fP=0
	Organization ID (env: GF_ORG_ID)


.SH SEE ALSO
\fBgf-provisioning(1)\fP
