.nh
.TH "GF-PROVISIONING-GET-CONTACTPOINTS-EXPORT" "1" "May 2026" "" ""

.SH NAME
gf-provisioning-get-contactpoints-export - Exports all contact points in provisioning file format


.SH SYNOPSIS
\fBgf provisioning get-contactpoints-export [flags]\fP


.SH DESCRIPTION
Exports all contact points in provisioning file format


.SH OPTIONS
\fB--decrypt\fP[=false]
	Whether any contained secure settings should be decrypted or left redacted. Redacted settings will contain RedactedValue instead. Currently, only org admin can view decrypted secure settings.

.PP
\fB--describe-response-jsonschema\fP[=false]
	Print the JSON Schema of the response payload and exit without calling the API

.PP
\fB--download\fP[=false]
	Whether to initiate a download of the file or not.

.PP
\fB--format\fP=""
	Format of the downloaded file. Supported yaml, json or hcl. Accept header can also be used, but the query parameter will take precedence. Default: "yaml"

.PP
\fB-h\fP, \fB--help\fP[=false]
	help for get-contactpoints-export

.PP
\fB--name\fP=""
	Filter by name

.PP
\fB--raw\fP[=false]
	Print the raw HTTP response body instead of the decoded payload


.SH OPTIONS INHERITED FROM PARENT COMMANDS
\fB--api-key\fP=""
	API Key to authenticate to grafana server (env: GF_API_KEY)

.PP
\fB--base-path\fP="/api"
	Base path for server: useful when using sever behind reverse proxy (env: GF_BASE_PATH)

.PP
\fB--basic-user-password\fP=""
	Basic authentication password (env: GF_BASIC_AUTH_USERNAME)

.PP
\fB--basic-user-username\fP=""
	Basic authentication username (env: GF_BASIC_AUTH_PASSWORD)

.PP
\fB--debug\fP[=false]
	Enable debug logging (env: GF_DEBUG)

.PP
\fB--host\fP="localhost:3000"
	Grafana server host (env: GF_HOST)

.PP
\fB--org-id\fP=0
	Organization ID (env: GF_ORG_ID)


.SH SEE ALSO
\fBgf-provisioning(1)\fP
