.nh
.TH "GF-PROVISIONING-GET-ALERT-RULES-EXPORT" "1" "May 2026" "" ""

.SH NAME
gf-provisioning-get-alert-rules-export - Exports all alert rules in provisioning file format


.SH SYNOPSIS
\fBgf provisioning get-alert-rules-export [flags]\fP


.SH DESCRIPTION
Exports all alert rules in provisioning file format

.PP
Response schema (GetAlertRulesExportOK.Payload):
  apiVersion                                                        number
  contactPoints                                                     array
  contactPoints[].name                                              string
  contactPoints[].orgId                                             number
  contactPoints[].receivers                                         array
  contactPoints[].receivers[].disableResolveMessage                 boolean
  contactPoints[].receivers[].settings                              object
  contactPoints[].receivers[].type                                  string
  contactPoints[].receivers[].uid                                   string
  groups                                                            array
  groups[].folder                                                   string
  groups[].interval                                                 string
  groups[].name                                                     string
  groups[].orgId                                                    number
  groups[].rules                                                    array
  groups[].rules[].annotations                                      map
  groups[].rules[].condition                                        string
  groups[].rules[].dashboardUid                                     string
  groups[].rules[].data                                             array
  groups[].rules[].data[].datasourceUid                             string
  groups[].rules[].data[].model                                     map
  groups[].rules[].data[].queryType                                 string
  groups[].rules[].data[].refId                                     string
  groups[].rules[].data[].relativeTimeRange                         object
  groups[].rules[].data[].relativeTimeRange.from                    number
  groups[].rules[].data[].relativeTimeRange.to                      number
  groups[].rules[].execErrState                                     string                enum: OK | Alerting | Error
  groups[].rules[].for                                              string
  groups[].rules[].isPaused                                         boolean
  groups[].rules[].keepFiringFor                                    string
  groups[].rules[].labels                                           map
  groups[].rules[].missing_series_evals_to_resolve                  number
  groups[].rules[].noDataState                                      string                enum: Alerting | NoData | OK
  groups[].rules[].notification_settings                            object
  groups[].rules[].notification_settings.active_time_intervals      array
  groups[].rules[].notification_settings.group_by                   array
  groups[].rules[].notification_settings.group_interval             string
  groups[].rules[].notification_settings.group_wait                 string
  groups[].rules[].notification_settings.mute_time_intervals        array
  groups[].rules[].notification_settings.receiver                   string
  groups[].rules[].notification_settings.repeat_interval            string
  groups[].rules[].panelId                                          number
  groups[].rules[].record                                           object
  groups[].rules[].record.from                                      string
  groups[].rules[].record.metric                                    string
  groups[].rules[].record.targetDatasourceUid                       string
  groups[].rules[].title                                            string
  groups[].rules[].uid                                              string
  muteTimes                                                         array
  muteTimes[].name                                                  string
  muteTimes[].orgId                                                 number
  muteTimes[].time_intervals                                        array
  muteTimes[].time_intervals[].name                                 string
  muteTimes[].time_intervals[].time_intervals                       array
  muteTimes[].time_intervals[].time_intervals[].days_of_month       array
  muteTimes[].time_intervals[].time_intervals[].location            string
  muteTimes[].time_intervals[].time_intervals[].months              array
  muteTimes[].time_intervals[].time_intervals[].times               array
  muteTimes[].time_intervals[].time_intervals[].times[].end_time    string
  muteTimes[].time_intervals[].time_intervals[].times[].start_time  string
  muteTimes[].time_intervals[].time_intervals[].weekdays            array
  muteTimes[].time_intervals[].time_intervals[].years               array
  policies                                                          array
  policies[].active_time_intervals                                  array
  policies[].continue                                               boolean
  policies[].group_by                                               array
  policies[].group_interval                                         string
  policies[].group_wait                                             string
  policies[].match                                                  map   Deprecated. Remove before v1.0 release.
  policies[].match_re                                               map
  policies[].matchers                                               array
  policies[].matchers[].Name                                        string
  policies[].matchers[].Type                                        number
  policies[].matchers[].Value                                       string
  policies[].mute_time_intervals                                    array
  policies[].object_matchers                                        array>
  policies[].orgId                                                  number
  policies[].receiver                                               string
  policies[].repeat_interval                                        string
  policies[].routes                                                 array
  policies[].routes[].active_time_intervals                         array
  policies[].routes[].continue                                      boolean
  policies[].routes[].group_by                                      array
  policies[].routes[].group_interval                                string
  policies[].routes[].group_wait                                    string
  policies[].routes[].match                                         map   Deprecated. Remove before v1.0 release.
  policies[].routes[].match_re                                      map
  policies[].routes[].matchers                                      array
  policies[].routes[].matchers[].Name                               string
  policies[].routes[].matchers[].Type                               number
  policies[].routes[].matchers[].Value                              string
  policies[].routes[].mute_time_intervals                           array
  policies[].routes[].object_matchers                               array>
  policies[].routes[].receiver                                      string
  policies[].routes[].repeat_interval                               string
  policies[].routes[].routes                                        array


.SH OPTIONS
\fB--describe-response-jsonschema\fP[=false]
	Print the JSON Schema of the response payload and exit without calling the API

.PP
\fB--download\fP[=false]
	Whether to initiate a download of the file or not.

.PP
\fB--folder-uid\fP=[]
	UIDs of folders from which to export rules

.PP
\fB--format\fP=""
	Format of the downloaded file. Supported yaml, json or hcl. Accept header can also be used, but the query parameter will take precedence. Default: "yaml"

.PP
\fB--group\fP=""
	Name of group of rules to export. Must be specified only together with a single folder UID

.PP
\fB-h\fP, \fB--help\fP[=false]
	help for get-alert-rules-export

.PP
\fB--raw\fP[=false]
	Print the raw HTTP response body instead of the decoded payload

.PP
\fB--rule-uid\fP=""
	UID of alert rule to export. If specified, parameters folderUid and group must be empty.


.SH OPTIONS INHERITED FROM PARENT COMMANDS
\fB--api-key\fP=""
	API Key to authenticate to grafana server (env: GF_API_KEY)

.PP
\fB--base-path\fP="/api"
	Base path for server: useful when using sever behind reverse proxy (env: GF_BASE_PATH)

.PP
\fB--basic-user-password\fP=""
	Basic authentication password (env: GF_BASIC_AUTH_USERNAME)

.PP
\fB--basic-user-username\fP=""
	Basic authentication username (env: GF_BASIC_AUTH_PASSWORD)

.PP
\fB--debug\fP[=false]
	Enable debug logging (env: GF_DEBUG)

.PP
\fB--host\fP="localhost:3000"
	Grafana server host (env: GF_HOST)

.PP
\fB--org-id\fP=0
	Organization ID (env: GF_ORG_ID)


.SH SEE ALSO
\fBgf-provisioning(1)\fP
