.nh
.TH "GF-PLAYLISTS" "1" "May 2026" "" ""

.SH NAME
gf-playlists - Playlists API


.SH SYNOPSIS
\fBgf playlists [flags]\fP


.SH DESCRIPTION
Playlists API


.SH OPTIONS
\fB-h\fP, \fB--help\fP[=false]
	help for playlists


.SH OPTIONS INHERITED FROM PARENT COMMANDS
\fB--api-key\fP=""
	API Key to authenticate to grafana server (env: GF_API_KEY)

.PP
\fB--base-path\fP="/api"
	Base path for server: useful when using sever behind reverse proxy (env: GF_BASE_PATH)

.PP
\fB--basic-user-password\fP=""
	Basic authentication password (env: GF_BASIC_AUTH_USERNAME)

.PP
\fB--basic-user-username\fP=""
	Basic authentication username (env: GF_BASIC_AUTH_PASSWORD)

.PP
\fB--debug\fP[=false]
	Enable debug logging (env: GF_DEBUG)

.PP
\fB--host\fP="localhost:3000"
	Grafana server host (env: GF_HOST)

.PP
\fB--org-id\fP=0
	Organization ID (env: GF_ORG_ID)


.SH SEE ALSO
\fBgf(1)\fP, \fBgf-playlists-create-playlist(1)\fP, \fBgf-playlists-delete-playlist(1)\fP, \fBgf-playlists-get-playlist(1)\fP, \fBgf-playlists-get-playlist-items(1)\fP, \fBgf-playlists-search-playlists(1)\fP, \fBgf-playlists-update-playlist(1)\fP
