.nh
.TH "GF-PROVISIONING-POST-CONTACTPOINTS" "1" "May 2026" "" ""

.SH NAME
gf-provisioning-post-contactpoints - Creates a contact point


.SH SYNOPSIS
\fBgf provisioning post-contactpoints [flags]\fP


.SH DESCRIPTION
Creates a contact point

.PP
Body schema (EmbeddedContactPoint):
{
  "disableResolveMessage": boolean,
  "name": string,
  "provenance": string,
  "settings": any,  // models.JSON
  "type": string,
  "uid": string
}
  name                     Name is used as grouping key in the UI. Contact points with the
                           same name will be grouped in the UI.
  provenance               provenance
                           Read Only: true
  settings                 REQUIRED
  type                     REQUIRED
                           enum: alertmanager | dingding | discord | email | googlechat | kafka | line | opsgenie | pagerduty | pushover | sensugo | slack | teams | telegram | threema | victorops | webhook | wecom
  uid                      UID is the unique identifier of the contact point. The UID can be
                           set by the user.
                           Max Length: 40
                           Min Length: 1


.SH OPTIONS
\fB--body\fP=""
	Request body JSON or path to a JSON file (e.g. --body=/path/to/body.json, --body='{"foo": "bar"}'). The 'Body schema' block is a type reference; use --describe-body-jsonschema for a strict JSON Schema.

.PP
\fB--describe-body-jsonschema\fP[=false]
	Print the JSON Schema of the request body and exit without calling the API

.PP
\fB--describe-response-jsonschema\fP[=false]
	Print the JSON Schema of the response payload and exit without calling the API

.PP
\fB-h\fP, \fB--help\fP[=false]
	help for post-contactpoints

.PP
\fB--raw\fP[=false]
	Print the raw HTTP response body instead of the decoded payload

.PP
\fB--x-disable-provenance\fP=""
	XDisableProvenance


.SH OPTIONS INHERITED FROM PARENT COMMANDS
\fB--api-key\fP=""
	API Key to authenticate to grafana server (env: GF_API_KEY)

.PP
\fB--base-path\fP="/api"
	Base path for server: useful when using sever behind reverse proxy (env: GF_BASE_PATH)

.PP
\fB--basic-user-password\fP=""
	Basic authentication password (env: GF_BASIC_AUTH_USERNAME)

.PP
\fB--basic-user-username\fP=""
	Basic authentication username (env: GF_BASIC_AUTH_PASSWORD)

.PP
\fB--debug\fP[=false]
	Enable debug logging (env: GF_DEBUG)

.PP
\fB--host\fP="localhost:3000"
	Grafana server host (env: GF_HOST)

.PP
\fB--org-id\fP=0
	Organization ID (env: GF_ORG_ID)


.SH SEE ALSO
\fBgf-provisioning(1)\fP
