.nh
.TH "GF-QUERY-HISTORY-SEARCH-QUERIES" "1" "May 2026" "" ""

.SH NAME
gf-query-history-search-queries - Queries history search


.SH SYNOPSIS
\fBgf query-history search-queries [flags]\fP


.SH DESCRIPTION
Queries history search

.PP
Returns a list of queries in the query history that matches the search criteria. Query history search supports pagination. Use the \fBlimit\fR parameter to control the maximum number of queries returned; the default limit is 100. You can also use the \fBpage\fR query parameter to fetch queries from any page other than the first one.

.PP
Response schema (SearchQueriesOK.Payload):
  result                               object
  result.page                          number
  result.perPage                       number
  result.queryHistory                  array
  result.queryHistory[].comment        string
  result.queryHistory[].createdAt      number
  result.queryHistory[].createdBy      number
  result.queryHistory[].datasourceUid  string
  result.queryHistory[].queries        object
  result.queryHistory[].starred        boolean
  result.queryHistory[].uid            string
  result.totalCount                    number


.SH OPTIONS
\fB--datasource-uid\fP=[]
	List of data source UIDs to search for

.PP
\fB--describe-response-jsonschema\fP[=false]
	Print the JSON Schema of the response payload and exit without calling the API

.PP
\fB--from\fP=0
	From range for the query history search

.PP
\fB-h\fP, \fB--help\fP[=false]
	help for search-queries

.PP
\fB--limit\fP=0
	Limit the number of returned results

.PP
\fB--only-starred\fP[=false]
	Flag indicating if only starred queries should be returned

.PP
\fB--page\fP=0
	Use this parameter to access hits beyond limit. Numbering starts at 1. limit param acts as page size.

.PP
\fB--raw\fP[=false]
	Print the raw HTTP response body instead of the decoded payload

.PP
\fB--search-string\fP=""
	Text inside query or comments that is searched for

.PP
\fB--sort\fP="time-desc"
	Sort method

.PP
\fB--to\fP=0
	To range for the query history search


.SH OPTIONS INHERITED FROM PARENT COMMANDS
\fB--api-key\fP=""
	API Key to authenticate to grafana server (env: GF_API_KEY)

.PP
\fB--base-path\fP="/api"
	Base path for server: useful when using sever behind reverse proxy (env: GF_BASE_PATH)

.PP
\fB--basic-user-password\fP=""
	Basic authentication password (env: GF_BASIC_AUTH_USERNAME)

.PP
\fB--basic-user-username\fP=""
	Basic authentication username (env: GF_BASIC_AUTH_PASSWORD)

.PP
\fB--debug\fP[=false]
	Enable debug logging (env: GF_DEBUG)

.PP
\fB--host\fP="localhost:3000"
	Grafana server host (env: GF_HOST)

.PP
\fB--org-id\fP=0
	Organization ID (env: GF_ORG_ID)


.SH SEE ALSO
\fBgf-query-history(1)\fP
