.nh
.TH "GF-QUERY-HISTORY" "1" "Apr 2026" "" ""

.SH NAME
gf-query-history - Query history API


.SH SYNOPSIS
\fBgf query-history [flags]\fP


.SH DESCRIPTION
Query history API


.SH OPTIONS
\fB-h\fP, \fB--help\fP[=false]
	help for query-history


.SH OPTIONS INHERITED FROM PARENT COMMANDS
\fB--api-key\fP=""
	API Key to authenticate to grafana server (env: GF_API_KEY)

.PP
\fB--base-path\fP="/api"
	Base path for server: useful when using sever behind reverse proxy (env: GF_BASE_PATH)

.PP
\fB--basic-user-password\fP=""
	Basic authentication password (env: GF_BASIC_AUTH_USERNAME)

.PP
\fB--basic-user-username\fP=""
	Basic authentication username (env: GF_BASIC_AUTH_PASSWORD)

.PP
\fB--debug\fP[=false]
	Enable debug logging (env: GF_DEBUG)

.PP
\fB--host\fP="localhost:3000"
	Grafana server host (env: GF_HOST)

.PP
\fB--org-id\fP=0
	Organization ID (env: GF_ORG_ID)


.SH SEE ALSO
\fBgf(1)\fP, \fBgf-query-history-create-query(1)\fP, \fBgf-query-history-delete-query(1)\fP, \fBgf-query-history-patch-query-comment(1)\fP, \fBgf-query-history-search-queries(1)\fP, \fBgf-query-history-star-query(1)\fP, \fBgf-query-history-unstar-query(1)\fP
