.nh
.TH "GF-REPORTS-UPDATE-REPORT" "1" "Apr 2026" "" ""

.SH NAME
gf-reports-update-report - Updates a report


.SH SYNOPSIS
\fBgf reports update-report [flags]\fP


.SH DESCRIPTION
Available to org admins only and with a valid or expired license.

.PP
You need to have a permission with action \fBreports.admin:write\fR with scope \fBreports:id:<report ID>\fR\&.

.PP
Requesting reports using the internal id will stop workgin in the future Use the reporting apiserver to manage reports.  See: /apis/reporting.grafana.app/

.PP
Body schema (CreateOrUpdateReport):
{
  "dashboards": [
    {
      "dashboard": object,
      "reportVariables": any,
      "timeRange": object
    }
  ],
  "enableCsv": boolean,
  "enableDashboardUrl": boolean,
  "formats": [string],
  "message": string,
  "name": string,
  "options": {
    "layout": string,
    "orientation": string,
    "pdfCombineOneFile": boolean,
    "pdfShowTemplateVariables": boolean,
    "timeRange": object
  },
  "recipients": string,
  "replyTo": string,
  "scaleFactor": number,
  "schedule": {
    "dayOfMonth": string,
    "endDate": string,
    "frequency": string,
    "intervalAmount": number,
    "intervalFrequency": string,
    "startDate": string,
    "timeZone": string,
    "workdaysOnly": boolean
  },
  "state": string,
  "subject": string
}


.SH OPTIONS
\fB--body\fP=""
	The path to the body json file or json string. For example, --body=/path/to/body.json or --body='{"foo": "bar"}'

.PP
\fB-h\fP, \fB--help\fP[=false]
	help for update-report

.PP
\fB--id\fP=0
	ID


.SH OPTIONS INHERITED FROM PARENT COMMANDS
\fB--api-key\fP=""
	API Key to authenticate to grafana server (env: GF_API_KEY)

.PP
\fB--base-path\fP="/api"
	Base path for server: useful when using sever behind reverse proxy (env: GF_BASE_PATH)

.PP
\fB--basic-user-password\fP=""
	Basic authentication password (env: GF_BASIC_AUTH_USERNAME)

.PP
\fB--basic-user-username\fP=""
	Basic authentication username (env: GF_BASIC_AUTH_PASSWORD)

.PP
\fB--debug\fP[=false]
	Enable debug logging (env: GF_DEBUG)

.PP
\fB--host\fP="localhost:3000"
	Grafana server host (env: GF_HOST)

.PP
\fB--org-id\fP=0
	Organization ID (env: GF_ORG_ID)


.SH SEE ALSO
\fBgf-reports(1)\fP
