.nh
.TH "GF-REPORTS-DELETE-REPORT" "1" "Jun 2026" "" ""

.SH NAME
gf-reports-delete-report - Deletes a report


.SH SYNOPSIS
\fBgf reports delete-report [flags]\fP


.SH DESCRIPTION
Deletes a report

.PP
Available to org admins only and with a valid or expired license.

.PP
You need to have a permission with action \fBreports.delete\fR with scope \fBreports:id:<report ID>\fR\&.

.PP
Requesting reports using the internal id will stop workgin in the future Use the reporting apiserver to manage reports.  See: /apis/reporting.grafana.app/

.PP
Response schema (DeleteReportOK.Payload):
  message  string


.SH OPTIONS
\fB--describe-response-jsonschema\fP[=false]
	Print the JSON Schema of the response payload and exit without calling the API

.PP
\fB-h\fP, \fB--help\fP[=false]
	help for delete-report

.PP
\fB--id\fP=0
	ID [required]

.PP
\fB--raw\fP[=false]
	Print the raw HTTP response body instead of the decoded payload


.SH OPTIONS INHERITED FROM PARENT COMMANDS
\fB--api-key\fP=""
	API Key to authenticate to grafana server (env: GF_API_KEY)

.PP
\fB--base-path\fP="/api"
	Base path for server: useful when using sever behind reverse proxy (env: GF_BASE_PATH)

.PP
\fB--basic-user-password\fP=""
	Basic authentication password (env: GF_BASIC_AUTH_USERNAME)

.PP
\fB--basic-user-username\fP=""
	Basic authentication username (env: GF_BASIC_AUTH_PASSWORD)

.PP
\fB--debug\fP[=false]
	Enable debug logging (env: GF_DEBUG)

.PP
\fB--host\fP="localhost:3000"
	Grafana server host (env: GF_HOST)

.PP
\fB--org-id\fP=0
	Organization ID (env: GF_ORG_ID)


.SH SEE ALSO
\fBgf-reports(1)\fP
