.nh
.TH "GF-REPORTS-GET-REPORT" "1" "Jun 2026" "" ""

.SH NAME
gf-reports-get-report - Gets a report


.SH SYNOPSIS
\fBgf reports get-report [flags]\fP


.SH DESCRIPTION
Gets a report

.PP
Available to org admins only and with a valid or expired license.

.PP
You need to have a permission with action \fBreports:read\fR with scope \fBreports:id:<report ID>\fR\&.

.PP
Requesting reports using the internal id will stop workgin in the future Use the reporting apiserver to manage reports.  See: /apis/reporting.grafana.app/

.PP
Response schema (GetReportOK.Payload):
  created                           string
  dashboards                        array
  dashboards[].dashboard            object
  dashboards[].dashboard.id         number
  dashboards[].dashboard.name       string
  dashboards[].dashboard.uid        string
  dashboards[].reportVariables      object
  dashboards[].timeRange            object
  dashboards[].timeRange.from       string
  dashboards[].timeRange.to         string
  enableCsv                         boolean
  enableDashboardUrl                boolean
  formats                           array
  id                                number
  message                           string
  name                              string
  options                           object
  options.csvEncoding               string
  options.layout                    string
  options.orientation               string
  options.pdfCombineOneFile         boolean
  options.pdfShowTemplateVariables  boolean
  options.timeRange                 object
  options.timeRange.from            string
  options.timeRange.to              string
  orgId                             number
  recipients                        string
  replyTo                           string
  scaleFactor                       number
  schedule                          object
  schedule.dayOfMonth               string
  schedule.endDate                  string
  schedule.frequency                string
  schedule.intervalAmount           number
  schedule.intervalFrequency        string
  schedule.startDate                string
  schedule.timeZone                 string
  schedule.workdaysOnly             boolean
  state                             string
  subject                           string
  uid                               string
  updated                           string
  userId                            number


.SH OPTIONS
\fB--describe-response-jsonschema\fP[=false]
	Print the JSON Schema of the response payload and exit without calling the API

.PP
\fB-h\fP, \fB--help\fP[=false]
	help for get-report

.PP
\fB--id\fP=0
	ID [required]

.PP
\fB--raw\fP[=false]
	Print the raw HTTP response body instead of the decoded payload


.SH OPTIONS INHERITED FROM PARENT COMMANDS
\fB--api-key\fP=""
	API Key to authenticate to grafana server (env: GF_API_KEY)

.PP
\fB--base-path\fP="/api"
	Base path for server: useful when using server behind reverse proxy (env: GF_BASE_PATH)

.PP
\fB--basic-user-password\fP=""
	Basic authentication password (env: GF_BASIC_AUTH_PASSWORD)

.PP
\fB--basic-user-username\fP=""
	Basic authentication username (env: GF_BASIC_AUTH_USERNAME)

.PP
\fB--debug\fP[=false]
	Enable debug logging (env: GF_DEBUG)

.PP
\fB--host\fP="localhost:3000"
	Grafana server host (env: GF_HOST)

.PP
\fB--org-id\fP=0
	Organization ID (env: GF_ORG_ID)

.PP
\fB--timeout\fP=30s
	Timeout for the HTTP request to the Grafana server; 0 disables it (env: GF_TIMEOUT)


.SH SEE ALSO
\fBgf-reports(1)\fP
