.nh
.TH "GF-SERVICE-ACCOUNTS-SEARCH-ORG-SERVICE-ACCOUNTS-WITH-PAGING" "1" "Apr 2026" "" ""

.SH NAME
gf-service-accounts-search-org-service-accounts-with-paging -


.SH SYNOPSIS
\fBgf service-accounts search-org-service-accounts-with-paging [flags]\fP


.SH DESCRIPTION

.SH OPTIONS
\fB--disabled\fP[=false]
	Disabled

.PP
\fB--expired-tokens\fP[=false]
	ExpiredTokens

.PP
\fB-h\fP, \fB--help\fP[=false]
	help for search-org-service-accounts-with-paging

.PP
\fB--page\fP=0
	The default value is 1.

.PP
\fB--perpage\fP=1000
	The default value is 1000.

.PP
\fB--query\fP=""
	It will return results where the query value is contained in one of the name. Query values with spaces need to be URL encoded.


.SH OPTIONS INHERITED FROM PARENT COMMANDS
\fB--api-key\fP=""
	API Key to authenticate to grafana server (env: GF_API_KEY)

.PP
\fB--base-path\fP="/api"
	Base path for server: useful when using sever behind reverse proxy (env: GF_BASE_PATH)

.PP
\fB--basic-user-password\fP=""
	Basic authentication password (env: GF_BASIC_AUTH_USERNAME)

.PP
\fB--basic-user-username\fP=""
	Basic authentication username (env: GF_BASIC_AUTH_PASSWORD)

.PP
\fB--debug\fP[=false]
	Enable debug logging (env: GF_DEBUG)

.PP
\fB--host\fP="localhost:3000"
	Grafana server host (env: GF_HOST)

.PP
\fB--org-id\fP=0
	Organization ID (env: GF_ORG_ID)


.SH SEE ALSO
\fBgf-service-accounts(1)\fP
