.nh
.TH "GF-SIGNED-IN-USER" "1" "Feb 2026" "" ""

.SH NAME
gf-signed-in-user -


.SH SYNOPSIS
\fBgf signed-in-user [flags]\fP


.SH DESCRIPTION

.SH OPTIONS
\fB-h\fP, \fB--help\fP[=false]
	help for signed-in-user


.SH OPTIONS INHERITED FROM PARENT COMMANDS
\fB--api-key\fP=""
	API Key to authenticate to grafana server (env: GF_API_KEY)

.PP
\fB--base-path\fP="/api"
	Base path for server: useful when using sever behind reverse proxy (env: GF_BASE_PATH)

.PP
\fB--basic-user-password\fP=""
	Basic authentication password (env: GF_BASIC_AUTH_USERNAME)

.PP
\fB--basic-user-username\fP=""
	Basic authentication username (env: GF_BASIC_AUTH_PASSWORD)

.PP
\fB--debug\fP[=false]
	Enable debug logging (env: GF_DEBUG)

.PP
\fB--host\fP="localhost:3000"
	Grafana server host (env: GF_HOST)

.PP
\fB--org-id\fP=0
	Organization ID (env: GF_ORG_ID)


.SH SEE ALSO
\fBgf(1)\fP, \fBgf-signed-in-user-change-user-password(1)\fP, \fBgf-signed-in-user-clear-help-flags(1)\fP, \fBgf-signed-in-user-get-signed-in-user(1)\fP, \fBgf-signed-in-user-get-signed-in-user-org-list(1)\fP, \fBgf-signed-in-user-get-signed-in-user-team-list(1)\fP, \fBgf-signed-in-user-get-user-auth-tokens(1)\fP, \fBgf-signed-in-user-get-user-preferences(1)\fP, \fBgf-signed-in-user-patch-user-preferences(1)\fP, \fBgf-signed-in-user-revoke-user-auth-token(1)\fP, \fBgf-signed-in-user-set-help-flag(1)\fP, \fBgf-signed-in-user-star-dashboard-by-uid(1)\fP, \fBgf-signed-in-user-unstar-dashboard-by-uid(1)\fP, \fBgf-signed-in-user-update-signed-in-user(1)\fP, \fBgf-signed-in-user-update-user-preferences(1)\fP, \fBgf-signed-in-user-user-set-using-org(1)\fP
