.nh
.TH "GF-SERVICE-ACCOUNTS-DELETE-TOKEN" "1" "Apr 2026" "" ""

.SH NAME
gf-service-accounts-delete-token - Deletes token deletes service account tokens


.SH SYNOPSIS
\fBgf service-accounts delete-token [flags]\fP


.SH DESCRIPTION
Deletes token deletes service account tokens

.PP
Required permissions (See note in the introduction
\[la]https://grafana.com/docs/grafana/latest/developers/http_api/serviceaccount/#service\-account\-api\[ra] for an explanation): action: \fBserviceaccounts:write\fR scope: \fBserviceaccounts:id:1\fR (single service account)

.PP
Requires basic authentication and that the authenticated user is a Grafana Admin.


.SH OPTIONS
\fB--describe-response-jsonschema\fP[=false]
	Print the JSON Schema of the response payload and exit without calling the API

.PP
\fB-h\fP, \fB--help\fP[=false]
	help for delete-token

.PP
\fB--raw\fP[=false]
	Print the raw HTTP response body instead of the decoded payload

.PP
\fB--service-account-id\fP=0
	ServiceAccountID

.PP
\fB--token-id\fP=0
	TokenID


.SH OPTIONS INHERITED FROM PARENT COMMANDS
\fB--api-key\fP=""
	API Key to authenticate to grafana server (env: GF_API_KEY)

.PP
\fB--base-path\fP="/api"
	Base path for server: useful when using sever behind reverse proxy (env: GF_BASE_PATH)

.PP
\fB--basic-user-password\fP=""
	Basic authentication password (env: GF_BASIC_AUTH_USERNAME)

.PP
\fB--basic-user-username\fP=""
	Basic authentication username (env: GF_BASIC_AUTH_PASSWORD)

.PP
\fB--debug\fP[=false]
	Enable debug logging (env: GF_DEBUG)

.PP
\fB--host\fP="localhost:3000"
	Grafana server host (env: GF_HOST)

.PP
\fB--org-id\fP=0
	Organization ID (env: GF_ORG_ID)


.SH SEE ALSO
\fBgf-service-accounts(1)\fP
