.nh
.TH "GF-SAML-POST-SLO" "1" "Jun 2026" "" ""

.SH NAME
gf-saml-post-slo - Its performs single logout s l o callback


.SH SYNOPSIS
\fBgf saml post-slo [flags]\fP


.SH DESCRIPTION
Its performs single logout s l o callback

.PP
There might be two possible requests: 1. Logout response (callback) when Grafana initiates single logout and IdP returns response to logout request. 2. Logout request when another SP initiates single logout and IdP sends logout request to the Grafana, or in case of IdP-initiated logout.


.SH OPTIONS
\fB-h\fP, \fB--help\fP[=false]
	help for post-slo

.PP
\fB--raw\fP[=false]
	Print the raw HTTP response body instead of the decoded payload

.PP
\fB--saml-request\fP=""
	SAMLRequest

.PP
\fB--saml-response\fP=""
	SAMLResponse


.SH OPTIONS INHERITED FROM PARENT COMMANDS
\fB--api-key\fP=""
	API Key to authenticate to grafana server (env: GF_API_KEY)

.PP
\fB--base-path\fP="/api"
	Base path for server: useful when using sever behind reverse proxy (env: GF_BASE_PATH)

.PP
\fB--basic-user-password\fP=""
	Basic authentication password (env: GF_BASIC_AUTH_USERNAME)

.PP
\fB--basic-user-username\fP=""
	Basic authentication username (env: GF_BASIC_AUTH_PASSWORD)

.PP
\fB--debug\fP[=false]
	Enable debug logging (env: GF_DEBUG)

.PP
\fB--host\fP="localhost:3000"
	Grafana server host (env: GF_HOST)

.PP
\fB--org-id\fP=0
	Organization ID (env: GF_ORG_ID)


.SH SEE ALSO
\fBgf-saml(1)\fP
