.nh
.TH "GF-SNAPSHOTS-GET-SHARING-OPTIONS" "1" "Apr 2026" "" ""

.SH NAME
gf-snapshots-get-sharing-options - Gets snapshot sharing settings


.SH SYNOPSIS
\fBgf snapshots get-sharing-options [flags]\fP


.SH DESCRIPTION
Gets snapshot sharing settings


.SH OPTIONS
\fB-h\fP, \fB--help\fP[=false]
	help for get-sharing-options

.PP
\fB--raw\fP[=false]
	Print the raw HTTP response body instead of the decoded payload


.SH OPTIONS INHERITED FROM PARENT COMMANDS
\fB--api-key\fP=""
	API Key to authenticate to grafana server (env: GF_API_KEY)

.PP
\fB--base-path\fP="/api"
	Base path for server: useful when using sever behind reverse proxy (env: GF_BASE_PATH)

.PP
\fB--basic-user-password\fP=""
	Basic authentication password (env: GF_BASIC_AUTH_USERNAME)

.PP
\fB--basic-user-username\fP=""
	Basic authentication username (env: GF_BASIC_AUTH_PASSWORD)

.PP
\fB--debug\fP[=false]
	Enable debug logging (env: GF_DEBUG)

.PP
\fB--host\fP="localhost:3000"
	Grafana server host (env: GF_HOST)

.PP
\fB--org-id\fP=0
	Organization ID (env: GF_ORG_ID)


.SH SEE ALSO
\fBgf-snapshots(1)\fP
