.nh
.TH "GF-SERVICE-ACCOUNTS-SEARCH-ORG-SERVICE-ACCOUNTS-WITH-PAGING" "1" "May 2026" "" ""

.SH NAME
gf-service-accounts-search-org-service-accounts-with-paging - Searches service accounts with paging


.SH SYNOPSIS
\fBgf service-accounts search-org-service-accounts-with-paging [flags]\fP


.SH DESCRIPTION
Searches service accounts with paging

.PP
Required permissions (See note in the introduction
\[la]https://grafana.com/docs/grafana/latest/developers/http_api/serviceaccount/#service\-account\-api\[ra] for an explanation): action: \fBserviceaccounts:read\fR scope: \fBserviceaccounts:*\fR

.PP
Response schema (SearchOrgServiceAccountsWithPagingOK.Payload):
  page                             number
  perPage                          number
  serviceAccounts                  array
  serviceAccounts[].accessControl  map
  serviceAccounts[].avatarUrl      string
  serviceAccounts[].id             number
  serviceAccounts[].isDisabled     boolean
  serviceAccounts[].isExternal     boolean
  serviceAccounts[].login          string
  serviceAccounts[].name           string
  serviceAccounts[].orgId          number
  serviceAccounts[].role           string
  serviceAccounts[].tokens         number
  serviceAccounts[].uid            string
  totalCount                       number                It can be used for pagination of the user list
                                                         E.g. if totalCount is equal to 100 users and
                                                         the perpage parameter is set to 10 then there are 10 pages of users.


.SH OPTIONS
\fB--describe-response-jsonschema\fP[=false]
	Print the JSON Schema of the response payload and exit without calling the API

.PP
\fB--disabled\fP[=false]
	Disabled

.PP
\fB--expired-tokens\fP[=false]
	ExpiredTokens

.PP
\fB-h\fP, \fB--help\fP[=false]
	help for search-org-service-accounts-with-paging

.PP
\fB--page\fP=0
	The default value is 1.

.PP
\fB--perpage\fP=1000
	The default value is 1000.

.PP
\fB--query\fP=""
	It will return results where the query value is contained in one of the name. Query values with spaces need to be URL encoded.

.PP
\fB--raw\fP[=false]
	Print the raw HTTP response body instead of the decoded payload


.SH OPTIONS INHERITED FROM PARENT COMMANDS
\fB--api-key\fP=""
	API Key to authenticate to grafana server (env: GF_API_KEY)

.PP
\fB--base-path\fP="/api"
	Base path for server: useful when using sever behind reverse proxy (env: GF_BASE_PATH)

.PP
\fB--basic-user-password\fP=""
	Basic authentication password (env: GF_BASIC_AUTH_USERNAME)

.PP
\fB--basic-user-username\fP=""
	Basic authentication username (env: GF_BASIC_AUTH_PASSWORD)

.PP
\fB--debug\fP[=false]
	Enable debug logging (env: GF_DEBUG)

.PP
\fB--host\fP="localhost:3000"
	Grafana server host (env: GF_HOST)

.PP
\fB--org-id\fP=0
	Organization ID (env: GF_ORG_ID)


.SH SEE ALSO
\fBgf-service-accounts(1)\fP
