.nh
.TH "GF" "1" "Feb 2026" "" ""

.SH NAME
gf - CLI for Grafana API


.SH SYNOPSIS
\fBgf [flags]\fP


.SH DESCRIPTION
Grafana API Client for command line operations with shell completions


.SH OPTIONS
\fB--api-key\fP=""
	API Key to authenticate to grafana server (env: GF_API_KEY)

.PP
\fB--base-path\fP="/api"
	Base path for server: useful when using sever behind reverse proxy (env: GF_BASE_PATH)

.PP
\fB--basic-user-password\fP=""
	Basic authentication password (env: GF_BASIC_AUTH_USERNAME)

.PP
\fB--basic-user-username\fP=""
	Basic authentication username (env: GF_BASIC_AUTH_PASSWORD)

.PP
\fB--debug\fP[=false]
	Enable debug logging (env: GF_DEBUG)

.PP
\fB-h\fP, \fB--help\fP[=false]
	help for gf

.PP
\fB--host\fP="localhost:3000"
	Grafana server host (env: GF_HOST)

.PP
\fB--org-id\fP=0
	Organization ID (env: GF_ORG_ID)


.SH SEE ALSO
\fBgf-access-control(1)\fP, \fBgf-access-control-provisioning(1)\fP, \fBgf-admin(1)\fP, \fBgf-admin-ldap(1)\fP, \fBgf-admin-provisioning(1)\fP, \fBgf-admin-users(1)\fP, \fBgf-annotations(1)\fP, \fBgf-convert-prometheus(1)\fP, \fBgf-dashboards(1)\fP, \fBgf-datasources(1)\fP, \fBgf-devices(1)\fP, \fBgf-enterprise(1)\fP, \fBgf-folders(1)\fP, \fBgf-group-attribute-sync(1)\fP, \fBgf-health(1)\fP, \fBgf-ldap-debug(1)\fP, \fBgf-library-elements(1)\fP, \fBgf-licensing(1)\fP, \fBgf-migrations(1)\fP, \fBgf-org(1)\fP, \fBgf-orgs(1)\fP, \fBgf-playlists(1)\fP, \fBgf-provisioning(1)\fP, \fBgf-query-history(1)\fP, \fBgf-recording-rules(1)\fP, \fBgf-reports(1)\fP, \fBgf-saml(1)\fP, \fBgf-search(1)\fP, \fBgf-service-accounts(1)\fP, \fBgf-signed-in-user(1)\fP, \fBgf-signing-keys(1)\fP, \fBgf-snapshots(1)\fP, \fBgf-sso-settings(1)\fP, \fBgf-sync-team-groups(1)\fP, \fBgf-teams(1)\fP, \fBgf-user(1)\fP, \fBgf-users(1)\fP
