version: 2

before:
  hooks:
    - go mod tidy
    - make gen

builds:
  - env:
      - CGO_ENABLED=0
    goos:
      - linux
      - windows
      - darwin
    goarch:
      - amd64
      - arm64
    main: ./cmd/gf
    binary: gf
    flags:
      - -trimpath
    ldflags:
      - -s -w -X main.version={{ .Version }}

archives:
  - format: tar.gz
    format_overrides:
      - goos: windows
        format: zip
